import {describe,it,expect} from 'vitest';
import {layoutJourney,nominalDay,occurrenceExecutions} from './journeyFlow';
import {materializeEmailHtml} from './emailPackageHtml';
import type {JourneyGraph,JourneyNode,PackageMessage} from './types';
import type {FrameworkActivity} from '../../utils/communicationOrchestrator';
const node=(key:string,type='WAIT',next:string|null=null,configuration={}):JourneyNode=>({key,name:key,type,configuration,outcomes:[{key:'out',next,label:'',metadata:{},arguments:{}}]});
const graph=(nodes:JourneyNode[]):JourneyGraph=>({name:'J',version:1,reference:'journeys/1',entry:{trigger:{},event:{},de:{},entryMode:null},goals:[],exitCriteria:[],nodes,roots:[],joins:[]});
describe('Fluxo de jornadas',()=>{
 it('mantém um nó no Join e tempos distintos dos dois percursos',()=>{const split=node('split','RANDOMSPLIT');split.outcomes=[{key:'a',label:'A',next:'wait',metadata:{},arguments:{}},{key:'b',label:'B',next:'sms',metadata:{},arguments:{}}];const g=graph([split,node('wait','WAIT','sms',{waitDuration:1,waitUnit:'DAYS'}),node('sms','SMSSYNC')]);const l=layoutJourney(g);expect(l.nodes.filter(n=>n.key==='sms')).toHaveLength(1);const sms=l.nodes.find(n=>n.key==='sms')!;expect(sms.timings).toHaveLength(2);expect(nominalDay(sms)).toBe('Dias 0–1');expect(l.edges.filter(e=>e.to==='sms')).toHaveLength(2);expect(new Set(l.nodes.map(n=>n.col+':'+n.row)).size).toBe(l.nodes.length);});
 it('Einstein não soma dias, espera por evento torna o dia variável',()=>{const g=graph([node('sto','STOWAIT','sms',{params:{slidingWindowHours:24}}),node('sms','SMSSYNC','event'),node('event','WAITUNTILEVENT','email'),node('email','EMAILV2')]);const l=layoutJourney(g);expect(l.nodes.find(n=>n.key==='sms')!.timings[0]).toMatchObject({days:0,windows:24});expect(nominalDay(l.nodes.find(n=>n.key==='email')!)).toBe('Dia variável');});
 it('não converte espera ausente em zero nem tempo do optimizer em data fixa',()=>{for(const value of [null,undefined,'',-1]){const l=layoutJourney(graph([node('w','WAIT','sms',{waitDuration:value,waitUnit:'DAYS'}),node('sms','SMSSYNC')]));expect(nominalDay(l.nodes.find(n=>n.key==='sms')!)).toBe('Dia variável');}const l=layoutJourney(graph([node('p','PATHOPTIMIZER','sms'),node('sms','SMSSYNC')]));expect(nominalDay(l.nodes.find(n=>n.key==='sms')!)).toBe('Dia variável');});
 it('recusa ciclo e destino não exportado',()=>{expect(()=>layoutJourney(graph([node('a','WAIT','b'),node('b','WAIT','a')]))).toThrow('cíclico');expect(()=>layoutJourney(graph([node('a','WAIT','missing')]))).toThrow('não exportada');});
 it('reuso não transfere métricas: exige jornada, atividade, canal e vínculo real',()=>{const m={journey_name:'JOR_AQS_X',activity_name:'a',content:{channel:'SMS'}} as PackageMessage;const a={id:'1',jornada:'JOR_AQUISICAO_X','Activity name / Taxonomia':'a',Canal:'SMS',template_id:'T'} as FrameworkActivity;const rows=[a,{...a,id:'2',jornada:'OTHER'},{...a,id:'3',template_id:null},{...a,id:'4',Canal:'E-mail'}];expect(occurrenceExecutions(m,[m],rows).map(r=>r.id)).toEqual(['1']);expect(occurrenceExecutions(m,[m,m],rows)).toEqual([]);expect(occurrenceExecutions(m,[m],rows,true).map(r=>r.id)).toEqual(['1','2']);});
 it('materializa slots e imagens embutidas sem publishedURL; remove scripts',()=>{const image={file:'YWJj',fileProperties:{fileName:'banner.png'}};const a={views:{html:{content:'<div data-key="body"></div><script>alert(1)</script>',slots:{body:{content:'<img onerror="bad()" src="{{mcpm#/entities/assets/1/data/fileProperties/publishedURL}}">'}}}}};const h=materializeEmailHtml(a,new Map([['1',image]]))!;expect(h).toContain('data:image/png;base64,YWJj');expect(h).not.toContain('<script');expect(h).not.toContain('onerror');});
});
