import React,{useEffect,useRef,useState,useMemo} from 'react';
import {X,Maximize2,Minimize2,ChevronLeft,ChevronRight,Loader2,ImageOff} from 'lucide-react';
import type {JourneyIndexItem,JourneyManifest,MessageMeta,JourneyReuse} from '../../../modules/sfmc-package/journeyV2';
import {messageFacets,manifestMessages} from '../../../modules/sfmc-package/journeyV2';
import type {PackageMessage} from '../../../modules/sfmc-package/types';
import type {FlowNode} from '../../../modules/sfmc-package/journeyFlow';
import {occurrenceExecutions,nominalDay} from '../../../modules/sfmc-package/journeyFlow';
import {readJourneyMessage,readJourneyResults,readJourneyReuse,readCurrentContent} from '../../../services/journeyReadService';
import {projectExecutions} from '../../../utils/executionProjection';
import {resolvePreview,type PreviewResolution} from '../../../utils/communicationVisualResolution';
import {cachedSignedUrl} from '../../../services/templateContentIndex';
import {MessagePreview} from '../previews/MessagePreview';
import {TemplateIdChips} from '../TemplateIdChips';
import {ExecutionResults} from './ExecutionResults';
import {TagRow,tagsFromFacets} from '../performance/contentUi';
import {usePeriod} from '../../../contexts/PeriodContext';
import {useBU} from '../../../contexts/BUContext';
import {useAppStore} from '../../../store/useAppStore';
import {facetNorm,canonFacet,facetsFromRecords} from '../../../utils/contentPerformanceModel';
import type {FrameworkActivity} from '../../../utils/communicationOrchestrator';
import {format} from 'date-fns';

export function SafeEmail({html,title}:{html:string;title:string}){
 const [height,setHeight]=useState(1000);const frame=useRef<HTMLIFrameElement>(null);
 const cleaned=useMemo(()=>{const doc=new DOMParser().parseFromString(html,'text/html');doc.querySelectorAll('script,iframe,object,embed,form').forEach(n=>n.remove());doc.querySelectorAll('*').forEach(el=>{for(const a of [...el.attributes])if(/^on/i.test(a.name)||((a.name==='href'||a.name==='src')&&/^\s*(javascript|vbscript):/i.test(a.value)))el.removeAttribute(a.name);});doc.querySelectorAll('a').forEach(a=>a.removeAttribute('href'));return '<!doctype html>'+doc.documentElement.outerHTML;},[html]);
 useEffect(()=>setHeight(1000),[html]);
 const measure=()=>{const d=frame.current?.contentDocument;if(d)setHeight(Math.max(400,Math.min(16000,Math.max(d.body.scrollHeight,d.documentElement.scrollHeight))));};
 return <iframe ref={frame} title={title} sandbox="allow-same-origin" srcDoc={cleaned} onLoad={()=>{measure();frame.current?.contentDocument?.querySelectorAll('img').forEach(i=>i.addEventListener('load',measure,{once:true}));}} tabIndex={-1} scrolling="no" style={{width:640,maxWidth:'100%',height,border:0,background:'white'}}/>;
}
export function InspectorVisual({res,title}:{res:PreviewResolution;title:string}){
 const [asset,setAsset]=useState<string|null>(null),[error,setError]=useState('');
 useEffect(()=>{let alive=true;setAsset(null);setError('');if(!res.assetPath)return;cachedSignedUrl(res.assetPath).then(async u=>res.kind==='catalog_html'?await fetch(u).then(r=>{if(!r.ok)throw Error('Arquivo indisponível');return r.text();}):u).then(v=>{if(alive)setAsset(v);}).catch(()=>{if(alive)setError('Falha ao carregar a peça.');});return()=>{alive=false;};},[res.assetPath,res.kind]);
 if(error)return <p role="alert" className="p-8 text-sm text-rose-700">{error}</p>;
 if(res.content?.email_html)return <SafeEmail html={res.content.email_html} title={title}/>;
 if(res.content)return <div className="mx-auto w-full max-w-[500px]"><MessagePreview content={res.content}/></div>;
 if(res.kind==='catalog_html'&&asset)return <SafeEmail html={asset} title={title}/>;
 if(res.kind==='catalog_image'&&asset)return <img src={asset} alt={title} referrerPolicy="no-referrer" className="mx-auto max-w-full"/>;
 if(res.assetPath)return <p className="flex items-center gap-2 p-8 text-sm"><Loader2 className="animate-spin" size={18}/>Carregando peça…</p>;
 return <div className="p-8 text-center text-sm text-slate-500"><ImageOff className="mx-auto mb-3"/>{res.detail}</div>;
}
export function filterJourneyRecords(rows:FrameworkActivity[],bus:string[],f:Record<string,any>,context:string,segment:string){
 const pair=context?JSON.parse(context) as string[]:null;
 return rows.filter(r=>{const facets=facetsFromRecords([r]);if(bus.length&&!bus.includes(r.BU||''))return false;
 for(const [key,values] of [['canal',f.canais],['segmento',f.segmentos],['parceiro',f.parceiros],['subgrupo',f.subgrupos]] as [string,string[]][]){if(values?.length&&!values.some(v=>facets[key as keyof typeof facets].some(x=>facetNorm(x)===facetNorm(canonFacet(key as any,v)))))return false;}
 if(f.jornadas?.length&&!f.jornadas.some((j:string)=>j.trim().toUpperCase().replace(/^JOR_AQUISICAO_/,'JOR_AQS_')===(r.jornada||'').trim().toUpperCase().replace(/^JOR_AQUISICAO_/,'JOR_AQS_')))return false;
 if(pair&&pair[0]!=='Sem classificação'&&!facets.frente.includes(pair[0]))return false;
 if(pair&&pair[1]!=='Origem não informada'&&!facets.parceiro.includes(pair[1]))return false;
 if(segment&&!facets.segmento.includes(segment))return false;return true;});
}
function ResultsTab({entry,meta,context,segment}:{entry:JourneyIndexItem;meta:MessageMeta;context:string;segment:string}){
 const {startDate,endDate}=usePeriod(),{selectedBUs}=useBU(),f=useAppStore(s=>s.viewSettings.filtrosGlobais);
 const [scope,setScope]=useState(false),[state,setState]=useState<{rows:FrameworkActivity[];error:string;loading:boolean}>({rows:[],error:'',loading:true});
 const start=format(startDate,'yyyy-MM-dd'),end=format(endDate,'yyyy-MM-dd');
 const filterKey=JSON.stringify([selectedBUs,f,context,segment]);
 useEffect(()=>{let alive=true;setState({rows:[],error:'',loading:true});readJourneyResults(entry.id,meta.occurrence_key,start,end,scope).then(r=>{if(!r.complete)throw Error('Recorte muito amplo para validar todos os grupos. Reduza o período.');const projected=projectExecutions(r.rows,r.reviews);const messages=manifestMessages(entry.messages),message=messages.find(m=>m.activity_key===meta.activity_key)!;const actual=occurrenceExecutions({...message,journey_name:entry.journey_name},messages,projected,scope);if(alive)setState({rows:filterJourneyRecords(actual,selectedBUs,f as Record<string,any>,context,segment),error:'',loading:false});}).catch(e=>{if(alive)setState({rows:[],error:e.message||'Falha nos resultados',loading:false});});return()=>{alive=false;};},[entry.id,meta.occurrence_key,start,end,scope,filterKey]);
 const duplicate=entry.messages.filter(m=>m.activity_name===meta.activity_name&&m.channel===meta.channel).length>1;
 return <div className="space-y-4"><div className="flex flex-wrap gap-2"><button className={`rounded border px-3 py-2 text-xs ${!scope?'bg-cyan-50':''}`} onClick={()=>setScope(false)}>Esta atividade</button><button className={`rounded border px-3 py-2 text-xs ${scope?'bg-cyan-50':''}`} onClick={()=>setScope(true)}>Usos dos templates vinculados</button></div><p className="text-xs text-slate-500">{start} a {end} · {scope?'IDs efetivamente vinculados, no recorte global':'Jornada + atividade + canal'}. Não comprova passagem pelos ramos nem versão enviada.</p>{duplicate&&!scope&&<p className="rounded bg-amber-50 p-3 text-xs text-amber-800">Activity Name repetido em vários nós: nenhuma soma atribuída automaticamente a esta ocorrência.</p>}{state.loading?<p role="status" className="text-sm">Carregando resultados do recorte…</p>:state.error?<p role="alert" className="text-sm text-rose-700">{state.error}</p>:<><div className="space-y-2">{[...new Set(state.rows.map(r=>r.template_id).filter(Boolean))].map(id=><div key={id!}><p className="mb-1 text-[10px] text-slate-500">Template efetivamente vinculado</p><TemplateIdChips id={id!}/></div>)}</div><ExecutionResults rows={state.rows}/></>}</div>;
}
export function CommunicationInspector({entry,manifest,meta,node,context,segment,onClose,onSelect,onReuse}:{entry:JourneyIndexItem;manifest:JourneyManifest;meta:MessageMeta;node?:FlowNode;context:string;segment:string;onClose:()=>void;onSelect:(key:string)=>void;onReuse:(r:JourneyReuse)=>void}){
 const [prepared,setPrepared]=useState<import('../../../services/journeyRenditions').Rendition|null>(null);
 const [focused,setFocused]=useState(true),[tab,setTab]=useState('communication'),[message,setMessage]=useState<PackageMessage|null>(null),[res,setRes]=useState<PreviewResolution|null>(null),[error,setError]=useState(''),[retry,setRetry]=useState(0),[reuse,setReuse]=useState<JourneyReuse[]|null>(null);
 const dialog=useRef<HTMLDivElement>(null),visual=useRef<HTMLDivElement>(null);
 useEffect(()=>{dialog.current?.focus();const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();e.stopPropagation();onClose();}if(e.key==='Tab'){const nodes=[...dialog.current?.querySelectorAll<HTMLElement>('button,[tabindex="0"]')||[]];const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',handler,true);return()=>document.removeEventListener('keydown',handler,true);},[onClose]);
 useEffect(()=>{let alive=true;setMessage(null);setRes(null);setPrepared(null);setError('');setTab('communication');setReuse(null);const stored=manifest.renditions?.[meta.activity_key];if(stored&&stored.content_fingerprint===meta.content_fingerprint)cachedSignedUrl(stored.full_path).then(url=>{if(alive)setPrepared({url,width:stored.width,height:stored.height,warnings:stored.warnings,source:stored.source,at:Date.now()});}).catch(()=>{});import('../../../services/journeyRenditions').then(async r=>{const cached=await r.cachedRendition(meta);if(cached&&alive)setPrepared(cached);}).catch(()=>{});readJourneyMessage(entry.id,meta.occurrence_key).then(async m=>{const current=meta.observed_template_id&&!(m.content.body_text||m.content.email_html)?await readCurrentContent(meta.observed_template_id):[];const r=resolvePreview({channel:m.content.channel,catalog:meta.catalog?[meta.catalog]:[],contents:new Map(meta.observed_template_id?[[meta.observed_template_id,current]]:[]),templateId:meta.observed_template_id,packContent:m.content});if(alive){setMessage(m);setRes(r);import('../../../services/journeyRenditions').then(r=>r.prepareRendition(meta)).then(p=>{if(alive)setPrepared(p);}).catch(()=>{});}}).catch(e=>{if(alive)setError(e.message||'Falha ao carregar comunicação.');});return()=>{alive=false;};},[entry.id,meta.occurrence_key,retry]);
 useEffect(()=>{if(tab!=='reuse')return;let alive=true;readJourneyReuse(entry.id,meta.occurrence_key).then(v=>{if(alive)setReuse(v);}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false;};},[tab,entry.id,meta.occurrence_key]);
 const i=entry.messages.findIndex(m=>m.activity_key===meta.activity_key),f=messageFacets(meta);
 return <div className="absolute inset-0 z-40 flex items-stretch justify-center bg-slate-950/35 p-3 sm:p-5" onClick={onClose}>
 <div ref={dialog} tabIndex={-1} role="dialog" aria-modal="true" aria-label="Leitor da comunicação" className={`flex min-h-0 w-full flex-col overflow-hidden rounded-2xl bg-white shadow-2xl outline-none ${focused?'max-w-[1450px]':'ml-auto max-w-[520px]'}`} onClick={e=>e.stopPropagation()}>
 <header className="flex shrink-0 items-center justify-between gap-2 border-b p-4"><div className="min-w-0"><h3 className="font-bold">{node?.number||i+1} · {meta.channel} · {node?nominalDay(node):'Dia não calculado'}</h3><p className="truncate text-xs text-slate-500">{meta.asset_name||'Nome da peça não informado'}</p></div><div className="flex gap-1"><button onClick={()=>onSelect(entry.messages[(i-1+entry.messages.length)%entry.messages.length].activity_key)} aria-label="Comunicação anterior" className="rounded p-2 hover:bg-slate-100"><ChevronLeft size={18}/></button><button onClick={()=>onSelect(entry.messages[(i+1)%entry.messages.length].activity_key)} aria-label="Próxima comunicação" className="rounded p-2 hover:bg-slate-100"><ChevronRight size={18}/></button><button onClick={()=>setFocused(v=>!v)} aria-label={focused?'Leitura compacta':'Ampliar comunicação'} className="rounded p-2 hover:bg-slate-100">{focused?<Minimize2 size={18}/>:<Maximize2 size={18}/>}</button><button onClick={onClose} aria-label="Fechar comunicação" className="rounded p-2 hover:bg-slate-100"><X size={18}/></button></div></header>
 <div className={`min-h-0 flex-1 ${focused?'grid grid-cols-1 md:grid-cols-[minmax(0,1fr)_400px]':'flex flex-col overflow-auto'}`}>
 <div ref={visual} className={`min-h-0 bg-slate-100 p-4 ${focused?'overflow-auto':'shrink-0'}`} data-journey-reader-preview><p className="mb-3 text-xs text-slate-600">{prepared?.source||res?.label||'Conteúdo da ocorrência'} · prévia não certifica envio histórico.</p>{error?<div className="rounded bg-rose-50 p-4 text-sm text-rose-700">{error}<button onClick={()=>setRetry(r=>r+1)} className="ml-3 underline">Tentar novamente</button></div>:prepared?<><img src={prepared.url} alt={meta.asset_name||meta.activity_name} className="mx-auto w-full max-w-[640px]"/>{prepared.warnings.map((w,i)=><p key={i} className="mt-2 text-xs text-amber-800">{w}</p>)}</>:!message||!res?<p role="status" className="flex items-center gap-2 p-6 text-sm"><Loader2 className="animate-spin" size={18}/>Carregando esta comunicação…</p>:<div className="mx-auto w-full max-w-[640px]"><InspectorVisual res={res} title={meta.activity_name}/></div>}</div>
 <div className={`min-h-0 border-l ${focused?'overflow-auto':'shrink-0'}`}><nav className="sticky top-0 z-10 flex border-b bg-white">{[['communication','Contexto'],['results','Resultados'],['reuse','Outros usos']].map(([k,label])=><button key={k} onClick={()=>setTab(k)} className={`flex-1 border-b-2 px-2 py-3 text-xs font-semibold ${tab===k?'border-cyan-600 text-cyan-800':'border-transparent text-slate-500'}`}>{label}</button>)}</nav><div className="space-y-4 p-4">{tab==='communication'?<>
 <div><p className="text-xs text-slate-400">Activity Name</p><p className="mt-1 break-all font-mono text-xs">{meta.activity_name}</p></div><div><p className="text-xs text-slate-400">ID observado no link · af_sub3</p><p className="mt-1 break-all font-mono text-xs">{meta.observed_template_id||'Não observado'}</p></div>{meta.observed_template_id&&<TemplateIdChips id={meta.observed_template_id}/>}
 <TagRow tags={tagsFromFacets(f,meta.contexts?.length?'Contexto histórico de activities; versão não comprovada':'Governança/ID; conferir origem')}/>
 <div className="rounded bg-slate-50 p-3 text-xs text-slate-600"><strong>Caminhos desta ocorrência</strong>{node?node.timings.map((t,n)=><p key={n} className="mt-2">{t.path.join(' → ')||'Caminho direto'} · {t.days===null?'Dia variável':'Dia '+t.days}{t.windows?' · até +'+t.windows+'h Einstein':''}</p>):<p className="mt-2">Caminho não calculado para este grafo.</p>}</div>
 {meta.is_optout&&<p className="rounded bg-slate-50 p-3 text-xs">Mensagem operacional/opt-out, preservada no fluxo.</p>}{meta.alerts.filter(a=>!a.startsWith('Mesmo af_sub3')).map((a,n)=><p key={n} className="rounded bg-amber-50 p-3 text-xs text-amber-800">{a}</p>)}<p className="text-[11px] text-slate-500">Jornada v{manifest.journey_version} do pack · importação {entry.import_id.slice(0,8)}. Reutilizar conteúdo não elimina o momento ou o ramo.</p>
 </>:tab==='results'?<ResultsTab entry={entry} meta={meta} context={context} segment={segment}/>:reuse===null?<p role="status" className="text-sm">Consultando outros usos…</p>:reuse.length===0?<p className="text-sm text-slate-500">Nenhum outro uso encontrado pelas chaves comprovadas.</p>:<><p className="text-xs text-slate-500">Mesma configuração, mesmo ID ou asset compartilhado são evidências diferentes. Não comprovam o conteúdo enviado.</p>{reuse.map(r=><button key={r.snapshot_id+r.occurrence_key} className="block w-full rounded-lg border p-3 text-left hover:bg-cyan-50" onClick={()=>onReuse(r)}><span className="text-xs font-semibold text-cyan-800">{r.evidence==='exact_content'?'Mesma configuração de conteúdo':r.evidence==='template_id'?'Mesmo Template ID':'Asset compartilhado na origem'}</span><p className="mt-1 break-all text-xs">{r.journey_name} · v{r.journey_version}</p><p className="mt-1 break-all text-[11px] text-slate-500">{r.activity_name}</p></button>)}</>}
 </div></div></div></div></div>;
}
