import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {GitBranch,Clock,Mail,MessageSquare,MessageCircle,Bell,LogOut,FilePen,Lightbulb,HelpCircle,ZoomIn,ZoomOut,Maximize,Loader2,X,AlertTriangle,RefreshCw} from 'lucide-react';
import type {JourneySnapshot,PackageMessage} from '../../../modules/sfmc-package/types';
import {JOURNEY_CHANNELS,layoutJourney,nominalDay,occurrenceExecutions,type FlowNode} from '../../../modules/sfmc-package/journeyFlow';
import {listJourneySnapshots,readJourneySnapshot,type JourneySummary} from '../../../services/journeyFlowService';
import {useReconciliation} from '../../../hooks/useReconciliation';
import {usePeriod} from '../../../contexts/PeriodContext';
import {useTemplateContentIndex} from '../../../services/templateContentIndex';
import {resolvePreview} from '../../../utils/communicationVisualResolution';
import {PreviewThumb} from '../previews/ContentPreview';
import {ChannelPreview} from '../performance/ChannelPreview';
import {TemplateIdChips} from '../TemplateIdChips';
import {ExecutionResults} from './ExecutionResults';
import {facetsFromRecords} from '../../../utils/contentPerformanceModel';
import {TagRow,tagsFromFacets} from '../performance/contentUi';
import {normalizeJourney} from '../../../modules/sfmc-package/parsePackage';
import {describeError} from '../../../services/communicationService';
import {findJourneyMessages,versionsForJourney,sortJourneyVersions} from '../../../modules/sfmc-package/journeyNavigation';
import {canalToId} from '../../../utils/taxonomy';
const CHANNEL_ICON:Record<string,typeof Mail>={EMAILV2:Mail,SMSSYNC:MessageSquare,WHATSAPPACTIVITY:MessageCircle,PUSHNOTIFICATIONACTIVITY:Bell};
function NodeIcon({node}:{node:FlowNode}){const diamond=['WAIT','MULTICRITERIADECISION','ENGAGEMENTDECISION','RANDOMSPLIT','STOWAIT','PATHOPTIMIZER'].includes(node.type);const Icon=CHANNEL_ICON[node.type]||({WAIT:Clock,STOWAIT:Lightbulb,EXIT:LogOut,UPDATECONTACTDATA:FilePen,ENGAGEMENTDECISION:GitBranch} as Record<string,typeof Mail>)[node.type]||HelpCircle;return <span className={`grid h-10 w-10 place-items-center text-white ${node.type==='EXIT'?'rounded-full bg-lime-500':diamond?(node.type==='STOWAIT'?'rotate-45 rounded bg-blue-950':'rotate-45 rounded bg-orange-500'):'rounded-lg bg-teal-400'}`}><Icon size={22} className={diamond?'-rotate-45':''}/></span>;}
const xy=(n:FlowNode,compact:boolean)=>({x:300+n.col*180,y:70+n.row*(compact?115:190)});
export function JourneyFlowView(){
 const rec=useReconciliation(),{index:contents}=useTemplateContentIndex(),period=usePeriod();
 const [summaries,setSummaries]=useState<JourneySummary[]>([]),[snapshot,setSnapshot]=useState<JourneySnapshot|null>(null),[id,setId]=useState(''),[selected,setSelected]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[compact,setCompact]=useState(false),[zoom,setZoom]=useState(.7),[templateScope,setTemplateScope]=useState(false),[search,setSearch]=useState(''),[messageSearch,setMessageSearch]=useState(''),[revision,setRevision]=useState(0),[previewWidth,setPreviewWidth]=useState(Math.min(450,window.innerWidth-64));
 const viewport=useRef<HTMLDivElement>(null),drag=useRef<{x:number;y:number;left:number;top:number}|null>(null);
 const refreshSeq=useRef(0);
 const refresh=useCallback(()=>{const request=++refreshSeq.current;setLoading(true);listJourneySnapshots().then(rows=>{if(request!==refreshSeq.current)return;rows=sortJourneyVersions(rows);setSummaries(rows);setRevision(r=>r+1);setId(prev=>rows.some(r=>r.id===prev)?prev:rows[0]?.id||'');setError('');}).catch(e=>{if(request===refreshSeq.current)setError(describeError(e));}).finally(()=>{if(request===refreshSeq.current)setLoading(false);});},[]);
 useEffect(()=>{refresh();window.addEventListener('sfmc-package-changed',refresh);return()=>{refreshSeq.current++;window.removeEventListener('sfmc-package-changed',refresh);};},[refresh]);
 useEffect(()=>{let alive=true;setSnapshot(null);setSelected(null);setTemplateScope(false);setMessageSearch('');if(!id)return;setLoading(true);readJourneySnapshot(id).then(s=>{if(alive){setSnapshot(s);setError('');}}).catch(e=>{if(alive)setError(describeError(e));}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[id,revision]);
 const layout=useMemo(()=>{try{return snapshot?{value:layoutJourney(snapshot.graph,compact),error:''}:{value:null,error:''};}catch(e){return {value:null,error:describeError(e)};}},[snapshot,compact]);
 const fit=()=>{if(viewport.current&&layout.value){setZoom(Math.min(1,Math.max(.15,(viewport.current.clientWidth-40)/layout.value.width)));viewport.current.scrollTo(0,0);}};
 useEffect(()=>{fit();},[snapshot?.id,compact]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!e.defaultPrevented)setSelected(null);};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const messages=snapshot?.messages||[],byMessage=useMemo(()=>new Map(messages.map(m=>[m.activity_key,m])),[messages]);
 const picked=selected?byMessage.get(selected):undefined;
 const node=layout.value?.nodes.find(n=>n.key===selected)||(picked?{...snapshot!.graph.nodes.find(n=>n.key===selected)!,number:messages.indexOf(picked)+1,col:0,row:0,timings:[{days:null,windows:null,path:[]}]} as FlowNode:undefined);
 const matches=useMemo(()=>findJourneyMessages(messages,messageSearch),[messages,messageSearch]);
 const openMessage=(key:string)=>{setSelected(key);setTemplateScope(false);};
 useEffect(()=>{if(!selected||!layout.value)return;const n=layout.value.nodes.find(n=>n.key===selected);if(!n)return;const frame=requestAnimationFrame(()=>{if(!viewport.current)return;const p=xy(n,compact);viewport.current.scrollTo({left:Math.max(0,p.x*zoom-viewport.current.clientWidth/2),top:Math.max(0,p.y*zoom-viewport.current.clientHeight/2)});});return()=>cancelAnimationFrame(frame);},[selected,compact,zoom,layout]);
 useEffect(()=>{const resize=()=>setPreviewWidth(Math.max(240,Math.min(450,window.innerWidth-64)));window.addEventListener('resize',resize);return()=>window.removeEventListener('resize',resize);},[]);
 const catalog=useMemo(()=>rec.catalog.map(c=>c.raw),[rec.catalog]);
 const res=(m:PackageMessage)=>resolvePreview({channel:m.content.channel,catalog,contents,packContent:m.content,templateId:m.utm.af_sub3});
 const rows=useMemo(()=>picked?occurrenceExecutions(picked,messages,rec.periodLinked,templateScope):[],[picked,messages,rec.periodLinked,templateScope]);
 const contextRows=useMemo(()=>picked?rec.periodLinked.filter(r=>normalizeJourney(r.jornada||'')===normalizeJourney(picked.journey_name)&&r['Activity name / Taxonomia']?.trim()===picked.activity_name&&canalToId(r.Canal)===canalToId(picked.content.channel)):[],[picked,rec.periodLinked]);
 const reuse=picked?messages.filter(m=>m.activity_key!==picked.activity_key&&m.content.channel===picked.content.channel&&(picked.asset_id?m.asset_id===picked.asset_id:JSON.stringify(m.content)===JSON.stringify(picked.content))):[];
 const duplicate=picked&&messages.filter(m=>m.activity_name===picked.activity_name&&m.content.channel===picked.content.channel).length>1;
 const focusPath=useMemo(()=>{const keys=new Set<string>();if(!selected||!layout.value)return keys;keys.add(selected);const visit=(key:string,up:boolean)=>{for(const e of layout.value!.edges){if((up?e.to:e.from)!==key)continue;const next=up?e.from:e.to;if(keys.has(next))continue;keys.add(next);visit(next,up);}};visit(selected,true);visit(selected,false);return keys;},[selected,layout]);
 const g=snapshot?.graph;const de=g?.entry.de,ev=g?.entry.event,tr=g?.entry.trigger;
 const journeyNames=[...new Set(summaries.map(s=>s.journey_name))].filter(n=>n.toLowerCase().includes(search.toLowerCase())).sort();
 const currentName=summaries.find(s=>s.id===id)?.journey_name;
 return <div className="flex h-full min-h-0 flex-col bg-slate-50" data-journey-flow style={{height:'calc(100dvh - 84px)',minHeight:640}}>
 <header className="border-b bg-white px-6 py-4"><h2 className="flex items-center gap-2 text-2xl font-bold text-slate-900"><GitBranch size={24}/>Fluxo de jornadas</h2><p className="mt-1 text-sm text-slate-600">Explore os caminhos, as comunicações e os resultados de cada régua.</p></header>
 <div className="flex flex-wrap items-end gap-3 border-b bg-white px-6 py-3"><label className="text-xs text-slate-500">Buscar jornada<input aria-label="Buscar jornada" value={search} onChange={e=>setSearch(e.target.value)} className="mt-1 block rounded-lg border p-2 text-sm" placeholder="Nome da jornada"/></label><label className="min-w-64 flex-1 text-xs text-slate-500">Jornada<select aria-label="Jornada" value={currentName||''} onChange={e=>setId(versionsForJourney(summaries,e.target.value)[0].id)} className="mt-1 block w-full rounded-lg border p-2 text-sm"><option value="" disabled>Selecione uma jornada</option>{currentName&&!journeyNames.includes(currentName)&&<option value={currentName}>{currentName} · selecionada</option>}{journeyNames.map(n=><option key={n}>{n}</option>)}</select></label><label className="text-xs text-slate-500">Versão do pack<select aria-label="Versão do pack" value={id} onChange={e=>setId(e.target.value)} className="mt-1 block max-w-72 rounded-lg border p-2 text-sm">{versionsForJourney(summaries,currentName||'').map(s=><option key={s.id} value={s.id}>Versão {s.journey_version} · {new Date(s.created_at).toLocaleDateString('pt-BR')} · {s.import_id.slice(0,8)}</option>)}</select></label><button onClick={refresh} aria-label="Atualizar jornadas" className="rounded-lg border p-2"><RefreshCw size={18}/></button></div>
 {error&&<p role="alert" className="m-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-800">{error}</p>}
 {loading&&<p role="status" className="flex gap-2 p-4 text-sm"><Loader2 className="animate-spin" size={16}/>Carregando jornada…</p>}
 {!loading&&!summaries.length&&!error&&<div className="m-6 rounded-xl border bg-white p-8 text-center"><GitBranch className="mx-auto mb-3 text-cyan-700"/><p>Os próximos packs analisados conservarão o fluxo completo aqui.</p><p className="mt-2 text-sm text-slate-500">Packs anteriores precisam ter sua estrutura reprocessada; as aprovações existentes são preservadas.</p></div>}
 {g&&<><div className="flex flex-wrap items-center gap-3 bg-teal-950 px-6 py-2.5 text-xs text-white"><span>{g.nodes.length} atividades</span><span>{messages.length} comunicações</span>{Object.entries(messages.reduce((a,m)=>({...a,[m.content.channel]:(a[m.content.channel]||0)+1}),{} as Record<string,number>)).map(([c,n])=><span key={c}>{n} {c}</span>)}<span className="ml-auto">Resultados: {period.startDate.toLocaleDateString('pt-BR')} – {period.endDate.toLocaleDateString('pt-BR')}</span></div>
 <div className="flex flex-wrap items-center gap-2 border-b bg-white px-6 py-2"><button onClick={()=>setZoom(z=>Math.max(.15,z-.15))} aria-label="Diminuir zoom" className="rounded border p-2"><ZoomOut size={16}/></button><span className="w-12 text-center text-xs">{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(2,z+.15))} aria-label="Aumentar zoom" className="rounded border p-2"><ZoomIn size={16}/></button><button onClick={fit} className="flex items-center gap-1 rounded border px-2 py-1.5 text-xs"><Maximize size={15}/>Ajustar à tela</button><label className="ml-2 flex items-center gap-2 text-xs"><input type="checkbox" checked={compact} onChange={e=>setCompact(e.target.checked)}/>Só fluxo</label><input aria-label="Buscar comunicação no fluxo" value={messageSearch} onChange={e=>setMessageSearch(e.target.value)} placeholder="Buscar ID, peça ou atividade" className="ml-2 w-56 rounded border px-2 py-1.5 text-xs"/><span className="ml-auto hidden text-xs text-slate-500 xl:block">Arraste o fundo para navegar · clique numa comunicação</span></div>
 {(messageSearch||layout.error)&&<div className="max-h-36 shrink-0 overflow-auto border-b bg-slate-50 px-6 py-2"><p className="mb-1 text-xs text-slate-500">{matches.length} comunicação(ões) {layout.error?'· consulte as fichas; grafo indisponível':'encontrada(s)'}</p><div className="flex flex-wrap gap-2">{matches.map(m=><button key={m.activity_key} onClick={()=>openMessage(m.activity_key)} className="max-w-80 truncate rounded border bg-white px-2 py-1 text-xs text-cyan-800" title={m.activity_name}>{layout.value?.nodes.find(n=>n.key===m.activity_key)?.number||messages.indexOf(m)+1} · {m.asset_name||m.utm.af_sub3||m.activity_name}</button>)}</div></div>}
 {layout.error&&<p role="alert" className="m-4 rounded border border-amber-200 bg-amber-50 p-3 text-sm">{layout.error}</p>}
 <div className="flex min-h-0 flex-1 flex-col lg:flex-row"><div ref={viewport} className="relative min-h-[440px] min-w-0 flex-1 overflow-auto bg-white" onPointerDown={e=>{if((e.target as HTMLElement).closest('button,input,select,a'))return;drag.current={x:e.clientX,y:e.clientY,left:e.currentTarget.scrollLeft,top:e.currentTarget.scrollTop};e.currentTarget.setPointerCapture(e.pointerId);}} onPointerMove={e=>{if(!drag.current)return;e.currentTarget.scrollLeft=drag.current.left-(e.clientX-drag.current.x);e.currentTarget.scrollTop=drag.current.top-(e.clientY-drag.current.y);}} onPointerUp={()=>drag.current=null} onPointerCancel={()=>drag.current=null}>
 {layout.value&&<div style={{width:layout.value.width*zoom,height:layout.value.height*zoom}}><div className="relative origin-top-left" style={{width:layout.value.width,height:layout.value.height,transform:`scale(${zoom})`}}>
 <svg width={layout.value.width} height={layout.value.height} className="pointer-events-none absolute inset-0">{layout.value.nodes.filter(n=>n.col===0).map(n=>{const p=xy(n,compact);return <path key={n.key} d={`M210 ${p.y}H${p.x-22}`} fill="none" stroke="#cbdced" strokeWidth={2}/>;})}{layout.value.edges.map((e,i)=>{const a=layout.value!.nodes.find(n=>n.key===e.from)!,b=layout.value!.nodes.find(n=>n.key===e.to)!,p=xy(a,compact),q=xy(b,compact),mid=p.x+65;const active=selected&&(focusPath.has(e.to)&&focusPath.has(e.from));return <g key={i}><path d={`M${p.x+22} ${p.y}H${mid}V${q.y}H${q.x-22}`} fill="none" stroke={active?'#0891b2':'#cbdced'} strokeWidth={active?3:2}/>{e.label&&<><rect x={mid+2} y={q.y-14} width={Math.min(110,e.label.length*6+10)} height={16} rx={2} fill="#edf2f7"/><text x={mid+6} y={q.y-2} fontSize={10} fill="#64748b">{e.label.slice(0,18)}</text></>}</g>})}</svg>
 <aside className="absolute left-5 top-7 w-[190px] rounded border bg-white p-4 text-center text-xs"><div className="mx-auto mb-3 grid h-12 w-12 place-items-center rounded-full bg-lime-500 text-white"><FilePen/></div><p className="mb-3 font-semibold text-slate-500">EXTENSÃO DE DADOS</p><p className="break-words">{de?.name||'Não vem no pack'}</p><p className="mt-4 text-[10px] text-slate-400">FILTRO</p><p>{tr?.description||ev?.metaData?.criteriaDescription||(tr?.configurationArguments?.criteria?'Critério exportado':'Sem filtro configurado')}</p><hr className="my-4"/><p className="font-semibold text-slate-500">AGENDAMENTO</p><p className="mt-2">{ev?.metaData?.scheduleFlowMode==='runOnce'?'Ao publicar · execução única':ev?.schedule?.frequency==='Daily'?'Diário configurado':ev?.metaData?.scheduleFlowMode||'Não vem no pack'}</p><p className="mt-4 text-[10px] text-slate-400">REENTRADA</p><p>{g.entry.entryMode==='SingleEntryAcrossAllVersions'?'Sem reentrada entre versões':g.entry.entryMode==='MultipleEntries'?'Permitida':g.entry.entryMode||'Não vem no pack'}</p></aside>
 {layout.value.nodes.map(n=>{const p=xy(n,compact),m=byMessage.get(n.key);const reused=m&&messages.some(other=>other.activity_key!==m.activity_key&&m.asset_id&&other.asset_id===m.asset_id);const alert=m&&(m.alerts.some(a=>!a.startsWith('Mesmo af_sub3'))||!m.utm.af_sub3);const label=n.type==='EXIT'?nominalDay(n).replace(/^Dia /,'Sai no dia '):n.type==='STOWAIT'?'OHE do Einstein':n.name;return <div key={n.key} className={`absolute w-[150px] -translate-x-1/2 text-center ${selected&&focusPath.has(n.key)?'rounded-lg bg-cyan-50 ring-1 ring-cyan-300':''}`} style={{left:p.x,top:p.y-20}}><div className="relative mx-auto w-10">{m&&<span className="absolute -top-7 left-1/2 -translate-x-1/2 whitespace-nowrap text-[11px] text-cyan-800">{nominalDay(n)}</span>}{m?<button onClick={()=>openMessage(n.key)} aria-label={`Abrir comunicação ${n.number}: ${m.activity_name}`}><NodeIcon node={n}/></button>:<NodeIcon node={n}/>} {n.number&&<span className="absolute -right-3 -top-2 rounded-full border-2 border-white bg-teal-950 px-1.5 text-[10px] text-white">{n.number}</span>}{reused&&<span title="Peça reutilizada em outra ocorrência" className="absolute -left-3 top-7 rounded-full bg-teal-50 px-1 text-xs text-teal-700">↻</span>}{alert&&<span title="Consultar evidências na ficha" className="absolute -right-3 top-7 rounded-full bg-amber-100 px-1 text-xs text-amber-700">!</span>}</div><p className="mx-auto mt-2 line-clamp-2 h-8 max-w-[140px] break-words text-xs leading-4 text-slate-700" title={label}>{label}</p>{n.type==='STOWAIT'&&<p className="text-[11px] text-blue-800">até +{n.configuration.params?.slidingWindowHours??'?'}h</p>}{!compact&&m&&<div className="mt-2 flex justify-center"><PreviewThumb res={res(m)} w={48} h={64} title={m.activity_name} onOpen={()=>openMessage(n.key)} showBadge={false}/></div>}</div>;})}
 </div></div>}
 </div>
 {picked&&node&&<aside aria-label="Ficha da comunicação" className="max-h-[calc(100vh-180px)] w-full shrink-0 overflow-auto border-l bg-white p-5 lg:w-[540px]">
 <div className="mb-4 flex items-start justify-between gap-3"><div><h3 className="font-semibold text-slate-900">{node.number} · {picked.content.channel} · {nominalDay(node)}</h3><p className="mt-1 text-xs text-slate-500">{picked.asset_name||'Peça sem nome no pack'}</p></div><button onClick={()=>setSelected(null)} aria-label="Fechar ficha" className="rounded border p-2"><X size={16}/></button></div>
 <div className="mb-4 flex justify-center"><ChannelPreview res={res(picked)} width={previewWidth} height={picked.content.channel==='SMS'?260:430} title={picked.activity_name} assetName={picked.asset_name}/></div>
 <dl className="mb-4 space-y-3 text-xs"><div><dt className="text-slate-400">Activity Name</dt><dd className="mt-1 break-all font-mono">{picked.activity_name}</dd></div><div><dt className="text-slate-400">ID observado no link · af_sub3</dt><dd className="mt-1 break-all font-mono">{picked.utm.af_sub3||'Não observado no pack'}</dd></div></dl>
 {picked.utm.af_sub3&&<div className="mb-3"><TemplateIdChips id={picked.utm.af_sub3}/></div>}
 <TagRow tags={tagsFromFacets(facetsFromRecords(contextRows),'Activities no período')}/>
 <h4 className="mb-2 mt-4 text-sm font-semibold">Caminhos até esta comunicação</h4>{layout.error?<p className="text-xs text-amber-800">Não foi possível calcular os caminhos deste grafo.</p>:node.timings.map((t,i)=><p key={i} className="mb-2 rounded bg-slate-50 p-2 text-xs text-slate-600">{t.path.join(' → ')||'Caminho direto'} · {t.days===null?'Dia variável':'Dia '+t.days}{t.windows===null?' · janela Einstein não informada':t.windows?' · janelas Einstein até +'+t.windows+'h':''}</p>)}
 {node.pathsLimited&&<p className="text-xs text-amber-800">Muitos caminhos: lista limitada; tempo não certificado.</p>}
 {reuse.length>0&&<div className="my-3 rounded bg-teal-50 p-3 text-xs text-teal-800">↻ Mesma peça, ocorrências distintas. {reuse.map(m=><button key={m.activity_key} className="ml-1 underline" onClick={()=>openMessage(m.activity_key)}>Ficha {layout.value?.nodes.find(n=>n.key===m.activity_key)?.number}</button>)}</div>}
 {picked.alerts.filter(a=>!a.startsWith('Mesmo af_sub3')).map((a,i)=><p key={i} className="my-2 rounded bg-amber-50 p-2 text-xs text-amber-800">{a}</p>)}
 <div className="mb-3 mt-5 flex gap-2 text-xs"><button onClick={()=>setTemplateScope(false)} className={`rounded border px-2 py-1 ${!templateScope?'bg-cyan-50 text-cyan-800':''}`}>Esta atividade</button><button onClick={()=>setTemplateScope(true)} className={`rounded border px-2 py-1 ${templateScope?'bg-cyan-50 text-cyan-800':''}`}>Usos dos templates vinculados</button></div>
 <p className="mb-3 text-[11px] text-slate-500">{templateScope?'Todas as atividades dos IDs efetivamente vinculados a este uso, no recorte global.':'Jornada + Activity Name + canal, no recorte global.'} O pack não certifica a versão enviada nem a passagem dos contatos por cada ramo.</p>
 {duplicate&&!templateScope&&<p className="mb-3 rounded bg-amber-50 p-2 text-xs text-amber-800">Activity Name repetido em mais de um nó: resultados não atribuídos automaticamente a esta ocorrência.</p>}
 {rec.loading?<p className="text-xs text-slate-500">Atualizando resultados…</p>:rec.error?<p role="alert" className="text-xs text-rose-700">{rec.error}</p>:<ExecutionResults rows={rows}/>}
 </aside>}
 </div>
 <footer className="border-t bg-white px-6 py-3 text-[11px] text-slate-500">Snapshot do pack · versão {g.version} · importação {snapshot.import_id.slice(0,8)}. Dias nominais somam esperas fixas; Einstein é uma janela adicional. {g.goals.length>0&&`Meta: ${g.goals.map(goal=>goal.description||goal.name).join(' · ')}. `}{g.exitCriteria.map(e=>e.metaData?.criteriaDescription||e.description).filter(Boolean).map((s,i)=><span key={i}>Saída global: {s}. </span>)}Sem contagem de contatos ou resultados por ramo inferidos.</footer>
 </>}
 </div>;
}
