import {createPortal} from 'react-dom';
import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {GitBranch,RefreshCw,Image,FileText,LocateFixed} from 'lucide-react';
import {usePeriod} from '../../../contexts/PeriodContext';
import {useBU} from '../../../contexts/BUContext';
import {useAuth} from '../../../context/AuthContext';
import {useAppStore} from '../../../store/useAppStore';
import {FullscreenButton} from '../../ui/FullscreenButton';
import {readJourneyIndex,readJourneyManifest,readJourneyResults,resetJourneyCache} from '../../../services/journeyReadService';
import type {JourneyIndexItem,JourneyManifest,JourneyReuse} from '../../../modules/sfmc-package/journeyV2';
import {contextKey,contextLabel,messageFacets,matchesContext,relatedPath} from '../../../modules/sfmc-package/journeyV2';
import {versionsForJourney} from '../../../modules/sfmc-package/journeyNavigation';
import {layoutJourney} from '../../../modules/sfmc-package/journeyFlow';
import {matchesFacets,facetOptions,type FacetFilters} from '../../../utils/contentPerformanceModel';
import {projectExecutions} from '../../../utils/executionProjection';
import {format} from 'date-fns';
import {JourneyViewport,type ViewportHandle} from './JourneyViewport';
import {CommunicationInspector,filterJourneyRecords} from './CommunicationInspector';

export function JourneyFlowView(){
 const {user}=useAuth(),period=usePeriod(),{selectedBUs}=useBU(),global=useAppStore(s=>s.viewSettings.filtrosGlobais);
 const [index,setIndex]=useState<JourneyIndexItem[]>([]),[manifest,setManifest]=useState<JourneyManifest|null>(null),[context,setContext]=useState(''),[segment,setSegment]=useState(''),[id,setId]=useState(''),[selected,setSelected]=useState<string|null>(null);
 const [error,setError]=useState(''),[loading,setLoading]=useState(true),[revision,setRevision]=useState(0),[compact,setCompact]=useState(false),[expanded,setExpanded]=useState(false),[nativeFull,setNativeFull]=useState(false),[search,setSearch]=useState(''),[filters,setFilters]=useState<FacetFilters>({});
 const [coverage,setCoverage]=useState<{linked:Set<string>;unlinked:Set<string>;ambiguous:Set<string>;loading:boolean;error:string}|null>(null),[status,setStatus]=useState('all'),[exporting,setExporting]=useState(''),[exportScope,setExportScope]=useState<'all'|'path'|'fiches'>('all');
 const root=useRef<HTMLDivElement>(null),viewport=useRef<ViewportHandle>(null),restore=useRef(false),trigger=useRef<HTMLElement|null>(null),coverageRequest=useRef(0),exportAbort=useRef<AbortController|null>(null),pendingReuse=useRef<string|null>(null);
 useEffect(()=>()=>{coverageRequest.current++;exportAbort.current?.abort();},[]);
 useEffect(()=>{const change=()=>{setNativeFull(document.fullscreenElement===root.current);requestAnimationFrame(()=>viewport.current?.fit());};document.addEventListener('fullscreenchange',change);return()=>document.removeEventListener('fullscreenchange',change);},[]);
 const fullTarget=useCallback(()=>root.current,[]),close=useCallback(()=>{setSelected(null);requestAnimationFrame(()=>trigger.current?.focus());},[]);
 useEffect(()=>{let alive=true;setLoading(true);readJourneyIndex().then(rows=>{if(!alive)return;setIndex(rows);setError('');if(!restore.current&&user){restore.current=true;try{const s=JSON.parse(sessionStorage.getItem('journey-v2:'+user.id)||'null');if(s&&rows.some(r=>r.id===s.id)){setContext(s.context||'');setSegment(s.segment||'');setId(s.id);}}catch{}}}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[revision,user?.id]);
 useEffect(()=>{const update=()=>{resetJourneyCache();setRevision(r=>r+1);setCoverage(null);};window.addEventListener('sfmc-package-changed',update);window.addEventListener('communication-links-changed',update);return()=>{window.removeEventListener('sfmc-package-changed',update);window.removeEventListener('communication-links-changed',update);};},[]);
 useEffect(()=>{let alive=true;setManifest(null);setSelected(null);setCoverage(null);setFilters({});setSearch('');setStatus('all');if(!id)return;setLoading(true);readJourneyManifest(id).then(m=>{if(alive){setManifest(m);setError('');if(pendingReuse.current){setSelected(pendingReuse.current);pendingReuse.current=null;}}}).catch(e=>{if(alive)setError(e.message)}).finally(()=>{if(alive)setLoading(false)});return()=>{alive=false;};},[id,revision]);
 useEffect(()=>{if(user&&id&&context&&segment)sessionStorage.setItem('journey-v2:'+user.id,JSON.stringify({id,context,segment}));},[user?.id,id,context,segment]);
 useEffect(()=>{coverageRequest.current++;setCoverage(null);},[id,period.startDate,period.endDate,JSON.stringify(global),JSON.stringify(selectedBUs),context,segment]);
 const entry=index.find(r=>r.id===id);
 const allowed=useMemo(()=>index.filter(j=>j.messages.some(m=>{const f=messageFacets(m);return !f.frente.length||selectedBUs.some(b=>f.frente.some(v=>v.toLowerCase()===b.toLowerCase()));})),[index,JSON.stringify(selectedBUs)]);
 const contexts=useMemo(()=>[...new Set(allowed.flatMap(j=>j.messages.flatMap(m=>contextKey(messageFacets(m)))))].sort((a,b)=>contextLabel(a).localeCompare(contextLabel(b),'pt-BR')),[allowed]);
 const contextJourneys=useMemo(()=>allowed.filter(j=>j.messages.some(m=>matchesContext(m,context,''))),[allowed,context]);
 const segments=useMemo(()=>[...new Set(contextJourneys.flatMap(j=>j.messages.filter(m=>matchesContext(m,context,'')).flatMap(m=>messageFacets(m).segmento.length?messageFacets(m).segmento:['Sem classificação'])))].sort(),[contextJourneys,context]);
 const eligible=useMemo(()=>contextJourneys.filter(j=>j.messages.some(m=>segment==='Sem classificação'?!messageFacets(m).segmento.length:matchesContext(m,context,segment))),[contextJourneys,context,segment]);
 const names=[...new Set(eligible.map(j=>j.journey_name))].sort(),scopeMismatch=!!id&&(!eligible.some(j=>j.id===id)||!contexts.includes(context));
 const layout=useMemo(()=>{if(!manifest)return {value:null,error:''};try{return {value:layoutJourney(manifest.graph,compact),error:''};}catch(e){return {value:null,error:(e as Error).message};}},[manifest,compact]);
 const messages=entry?.messages||[];
 const matched=useMemo(()=>new Set(messages.filter(m=>{const f=messageFacets(m),text=[m.activity_name,m.asset_name,m.observed_template_id,m.channel].join(' ').toLocaleLowerCase('pt-BR');return matchesContext(m,context,segment==='Sem classificação'?'':segment)&&matchesFacets(f,filters)&&(!search||text.includes(search.toLocaleLowerCase('pt-BR')))&&(status==='all'||status==='no_id'&&!m.observed_template_id||status==='linked'&&coverage?.linked.has(m.activity_key)||status==='unlinked'&&coverage?.unlinked.has(m.activity_key));}).map(m=>m.activity_key)),[messages,context,segment,filters,search,status,coverage]);
 const activeFilters=matched.size<messages.length||!!search||Object.values(filters).some(v=>v&&v!=='all')||status!=='all';
 const path=useMemo(()=>{const keys=new Set<string>();if(layout.value){const targets=selected?[selected]:activeFilters?[...matched]:[];targets.forEach(k=>relatedPath(layout.value!,k).forEach(v=>keys.add(v)));}return keys;},[selected,matched,layout,activeFilters]);
 const onOpen=useCallback((key:string)=>{if(!root.current?.querySelector('[role=dialog]'))trigger.current=document.activeElement as HTMLElement;setSelected(key);},[]);
 const onReuse=useCallback((r:JourneyReuse)=>{const e=index.find(j=>j.id===r.snapshot_id);if(!e)return;const m=e.messages.find(m=>m.activity_key===r.activity_key);if(m){const f=messageFacets(m);setContext(contextKey(f)[0]);setSegment(f.segmento[0]||'Sem classificação');}if(e.id===id){setSelected(r.activity_key);}else{pendingReuse.current=r.activity_key;setId(e.id);setSelected(null);}},[index,id]);
 const loadCoverage=async()=>{if(!entry)return;const request=++coverageRequest.current;setCoverage({linked:new Set(),unlinked:new Set(),ambiguous:new Set(),loading:true,error:''});try{const r=await readJourneyResults(entry.id,'',format(period.startDate,'yyyy-MM-dd'),format(period.endDate,'yyyy-MM-dd'),false);if(!r.complete)throw Error('Recorte amplo demais para validar os grupos.');const rows=filterJourneyRecords(projectExecutions(r.rows,r.reviews),selectedBUs,global as Record<string,any>,context,segment);const linked=new Set<string>(),unlinked=new Set<string>(),ambiguous=new Set<string>();for(const m of entry.messages){if(m.is_optout||!matchesContext(m,context,segment==='Sem classificação'?'':segment))continue;const rs=rows.filter(a=>a['Activity name / Taxonomia']===m.activity_name&&a.Canal===m.channel);if(rs.length&&entry.messages.filter(other=>other.activity_name===m.activity_name&&other.channel===m.channel).length>1)ambiguous.add(m.activity_key);else if(rs.some(a=>a.template_id))linked.add(m.activity_key);else if(rs.length)unlinked.add(m.activity_key);}if(request===coverageRequest.current)setCoverage({linked,unlinked,ambiguous,loading:false,error:''});}catch(e){if(request===coverageRequest.current)setCoverage({linked:new Set(),unlinked:new Set(),ambiguous:new Set(),loading:false,error:(e as Error).message});}};
 const doExport=async(kind:'png'|'pdf')=>{if(!entry||!manifest||!layout.value)return;exportAbort.current=new AbortController();setExporting('Preparando recursos…');setError('');try{const {exportJourney}=await import('./journeyExport');await exportJourney({entry,manifest,layout:layout.value,compact,scope:exportScope,highlight:path,period:{start:format(period.startDate,'yyyy-MM-dd'),end:format(period.endDate,'yyyy-MM-dd')},context,segment,kind,onProgress:setExporting,signal:exportAbort.current.signal});}catch(e){setError((e as Error).name==='AbortError'?'Exportação cancelada.':'Não foi possível exportar: '+(e as Error).message);}finally{setExporting('');}};
 const reader=selected&&entry&&manifest&&entry.messages.find(m=>m.activity_key===selected)?<CommunicationInspector entry={entry} manifest={manifest} meta={entry.messages.find(m=>m.activity_key===selected)!} node={layout.value?.nodes.find(n=>n.key===selected)} context={context} segment={segment} onClose={close} onSelect={onOpen} onReuse={onReuse}/>:null;
 const workspace=<section ref={root} className={`flex min-h-0 flex-col overflow-auto md:overflow-hidden bg-slate-50 ${expanded?'fixed inset-0 z-[95]':'relative'}`} style={{height:expanded||nativeFull?'100dvh':'calc(100dvh - 140px)',minHeight:360}} data-journey-flow>
 <header className="shrink-0 border-b bg-white px-4 py-3"><div className="flex items-center justify-between gap-3"><h2 className="flex items-center gap-2 text-xl font-bold"><GitBranch size={22}/>Fluxo de jornadas</h2><div className="flex items-center gap-1"><button onClick={()=>{resetJourneyCache();setRevision(r=>r+1);}} aria-label="Atualizar jornadas" className="rounded p-2 hover:bg-slate-100"><RefreshCw size={17}/></button>{expanded?<button onClick={()=>setExpanded(false)} className="rounded border px-2 py-1 text-xs">Sair do modo expandido</button>:<FullscreenButton target={fullTarget} onFailure={()=>setExpanded(true)}/>}</div></div>
 <div className="mt-3 grid gap-2 sm:grid-cols-[minmax(160px,1fr)_minmax(140px,1fr)_minmax(230px,2fr)_minmax(110px,.8fr)]">
 <label className="text-[11px] text-slate-500">Parceiro / B2C<select aria-label="Parceiro / B2C" value={context} onChange={e=>{setContext(e.target.value);setSegment('');setId('');}} className="mt-1 w-full rounded-lg border p-2 text-xs text-slate-800"><option value="">Escolha o contexto</option>{contexts.map(k=><option key={k} value={k}>{contextLabel(k)}</option>)}</select></label>
 <label className="text-[11px] text-slate-500">Segmento<select aria-label="Segmento" disabled={!context} value={segment} onChange={e=>{setSegment(e.target.value);setId('');}} className="mt-1 w-full rounded-lg border p-2 text-xs text-slate-800 disabled:bg-slate-100"><option value="">Escolha o segmento</option>{segments.map(k=><option key={k}>{k}</option>)}</select></label>
 <label className="text-[11px] text-slate-500">Jornada<select aria-label="Jornada" disabled={!context||!segment} value={entry?.journey_name||''} onChange={e=>setId(versionsForJourney(eligible,e.target.value)[0].id)} className="mt-1 w-full rounded-lg border p-2 text-xs text-slate-800 disabled:bg-slate-100"><option value="">Escolha a jornada</option>{names.map(n=><option key={n}>{n}</option>)}</select></label>
 <label className="text-[11px] text-slate-500">Versão do pack<select aria-label="Versão do pack" disabled={!id} value={id} onChange={e=>setId(e.target.value)} className="mt-1 w-full rounded-lg border p-2 text-xs text-slate-800 disabled:bg-slate-100"><option value="">—</option>{entry&&versionsForJourney(eligible,entry.journey_name).map(j=><option key={j.id} value={j.id}>v{j.journey_version} · {new Date(j.created_at).toLocaleDateString('pt-BR')}</option>)}</select></label></div></header>
 {error&&<p role="alert" className="shrink-0 bg-rose-50 px-4 py-2 text-xs text-rose-700">{error}</p>}
 {scopeMismatch&&<p role="alert" className="shrink-0 bg-amber-50 px-4 py-2 text-xs text-amber-800">A seleção não corresponde aos filtros globais. Escolha outro contexto.</p>}
 {!manifest||!entry||scopeMismatch?<div className="grid min-h-0 flex-1 place-items-center p-8 text-center"><div><GitBranch className="mx-auto mb-4 text-cyan-700" size={38}/><p className="font-semibold">{loading?'Carregando o índice…':'Escolha um contexto, um segmento e uma jornada'}</p><p className="mt-2 text-sm text-slate-500">O fluxo carrega após a seleção. Prévias e resultados são consultados quando você abre a comunicação.</p></div></div>:<>
 <div className="flex shrink-0 flex-wrap items-center gap-3 bg-teal-950 px-4 py-2 text-[11px] text-white"><span>Estrutura: {manifest.graph.nodes.length} atividades</span><span>{messages.filter(m=>!m.is_optout).length} comunicações de campanha</span><span>{messages.filter(m=>m.is_optout).length} operacionais</span><span>{matched.size} no filtro</span><span className="ml-auto">Resultados: {format(period.startDate,'dd/MM/yyyy')} – {format(period.endDate,'dd/MM/yyyy')}</span><button onClick={loadCoverage} disabled={coverage?.loading} className="rounded border border-white/30 px-2 py-1">{coverage?.loading?'Consultando…':coverage?`${coverage.linked.size} com vínculo · ${coverage.unlinked.size} sem template${coverage.ambiguous.size?' · '+coverage.ambiguous.size+' ambíguas':''}`:'Ver cobertura do período'}</button></div>
 {coverage?.error&&<p role="alert" className="shrink-0 px-4 py-2 text-xs text-rose-700">{coverage.error}</p>}
 <div className="flex shrink-0 flex-wrap items-center gap-2 border-b bg-white px-4 py-2"><input aria-label="Buscar comunicação no fluxo" placeholder="ID, peça ou Activity Name" value={search} onChange={e=>setSearch(e.target.value)} className="w-48 rounded border px-2 py-1.5 text-xs"/>
 {(['canal','subgrupo','oferta','promocional','momento'] as const).map(k=><select key={k} aria-label={`Filtro ${k}`} value={filters[k]||'all'} onChange={e=>setFilters(f=>({...f,[k]:e.target.value}))} className="max-w-44 rounded border px-2 py-1.5 text-xs"><option value="all">{({canal:'Canal',subgrupo:'Subgrupo',oferta:'Oferta',promocional:'Promocional',momento:'Momento'})[k]}: todos</option>{facetOptions(messages.map(messageFacets),k).map(o=><option key={o.value} value={o.value}>{o.value} ({o.count})</option>)}</select>)}
 <select aria-label="Situação do vínculo" value={status} onChange={e=>{setStatus(e.target.value);if((e.target.value==='linked'||e.target.value==='unlinked')&&!coverage)void loadCoverage();}} className="rounded border px-2 py-1.5 text-xs"><option value="all">Vínculo: todos</option><option value="no_id">Sem ID no link</option><option value="linked">Com execução vinculada</option><option value="unlinked">Execução sem template</option></select>
 <label className="flex items-center gap-1 text-xs"><input type="checkbox" checked={compact} onChange={e=>setCompact(e.target.checked)}/>Só fluxo</label><button onClick={()=>{setFilters({});setSearch('');setStatus('all');}} className="text-xs text-cyan-800">Limpar filtros</button>
 <div className="ml-auto flex items-center gap-1"><select aria-label="Escopo da exportação" value={exportScope} onChange={e=>setExportScope(e.target.value as typeof exportScope)} className="rounded border px-2 py-1 text-xs"><option value="all">Fluxo completo</option><option value="path">Caminho destacado</option><option value="fiches">Fluxo + fichas</option></select><button onClick={()=>void doExport('png')} disabled={!!exporting||!layout.value} className="flex items-center gap-1 rounded border px-2 py-1.5 text-xs"><Image size={14}/>Salvar PNG</button><button onClick={()=>void doExport('pdf')} disabled={!!exporting||!layout.value} className="flex items-center gap-1 rounded border px-2 py-1.5 text-xs"><FileText size={14}/>Salvar PDF</button></div></div>
 {(search||Object.values(filters).some(v=>v&&v!=='all')||status!=='all')&&<div className="flex max-h-20 shrink-0 flex-wrap gap-1 overflow-auto border-b bg-slate-50 px-4 py-2">{messages.filter(m=>matched.has(m.activity_key)).map(m=><button key={m.activity_key} onClick={()=>viewport.current?.focus(m.activity_key)} className="flex max-w-64 items-center gap-1 truncate rounded border bg-white px-2 py-1 text-[11px] text-cyan-800" title={m.activity_name}><LocateFixed size={12}/>{messageFacets(m).momento[0]||m.channel} · {m.asset_name||m.observed_template_id||m.activity_name}</button>)}{matched.size===0&&<span className="text-xs text-slate-500">Nenhuma mensagem neste filtro; a estrutura foi preservada.</span>}</div>}
 {exporting&&<p role="status" className="shrink-0 bg-cyan-50 px-4 py-2 text-xs text-cyan-800">{exporting}<button onClick={()=>exportAbort.current?.abort()} className="ml-3 underline">Cancelar</button></p>}
 <div className="relative flex min-h-[360px] md:min-h-0 flex-1">{layout.value?<JourneyViewport ref={viewport} manifest={manifest} layout={layout.value} messages={messages} compact={compact} focus={path} matches={activeFilters?matched:null} onOpen={onOpen}/>:<div className="flex-1 overflow-auto p-6"><p role="alert" className="mb-4 text-sm text-amber-800">{layout.error}</p>{messages.map(m=><button key={m.activity_key} onClick={()=>onOpen(m.activity_key)} className="mb-2 block rounded border bg-white p-3 text-sm">{m.asset_name||m.activity_name}</button>)}</div>}
 </div>
 <footer className="shrink-0 border-t bg-white px-4 py-2 text-[10px] text-slate-500">Fonte: pack v{manifest.journey_version} · classificação com proveniência. Dias nominais não incluem espera variável. Versão enviada e passagem de contatos por ramos não são comprovadas pelo pack.</footer>
 </>}
 {reader}</section>;
 return expanded?createPortal(workspace,document.body):workspace;
}
