import {describe,it,expect} from 'vitest';
import {parseJornadaIdentity,resolveDim} from './taxonomy';
import {runReconciliationGoldenSet} from './taxonomy.goldenset';
import {orchestrateCommunication,type FrameworkActivity} from './communicationOrchestrator';
import type {ProposalRow} from '../services/communicationProposalService';
const row=()=>({id:'p',proposed_template_id:'b2c_car21_vibe_srsa_DispD2',resolved_context:{partner:'Serasa',segment:'Abandonados',subgroup:'21D',campaign:'Vibe'},message:{payload:{journey_name:'JOR_AQS_B2C_PROPRI_ABD_CARRINHO21D_PADRAO_21DIAS_SET26',activity_name:'carrinho21dserasa',content:{channel:'WhatsApp'},paths:[],utm:{}}}} as unknown as ProposalRow);
const activity=(patch:Partial<FrameworkActivity>={})=>({id:'a',jornada:row().message.payload.journey_name,'Activity name / Taxonomia':'carrinho21dserasa',Canal:'WhatsApp',BU:'B2C',Parceiro:'Serasa',Segmento:'Abandonados',Oferta:'Padrao',Promocional:'Vibe','Base Total':100,'Base Acionável':80,'Data de Disparo':'2026-09-24T03:00:00Z',...patch} as FrameworkActivity);
describe('communication orchestration',()=>{
 it('preserves the historical matcher golden set and recognizes Vibe and AQS',()=>{expect(runReconciliationGoldenSet().failed).toBe(0);expect(resolveDim('campanha','b2c_email_vibe_bsp_S1D01')).toBe('vibe');expect(parseJornadaIdentity('JOR_AQS_B2B2C_DIA_CRM_TEST').segmento).toBe('crm');});
 it('isolates execution metrics by journey and channel, leaving other contexts visible',()=>{const o=orchestrateCommunication(row(),[activity(),activity({id:'b',jornada:'OUTRA','Base Total':900}),activity({id:'c',Canal:'SMS','Base Total':800})],[],[]);expect(o.base).toBe(100);expect(o.actionable).toBe(80);expect(o.exec).toBe(1);expect(o.otherContexts).toBe(2);});
 it('preserves null and limits metrics using São Paulo dates',()=>{const o=orchestrateCommunication(row(),[activity({'Base Total':null}),activity({id:'b','Data de Disparo':'2026-09-25T01:00:00Z'})],[],[],{start:'2026-09-24',end:'2026-09-24'});expect(o.exec).toBe(2);expect(o.base).toBeNull();expect(o.actionable).toBe(160);});
 it('keeps offer and promotional separate and flags Serasa versus proprietary',()=>{const o=orchestrateCommunication(row(),[activity({Parceiro:'Proprietaria',Promocional:'Copa'})],[],[]);expect(o.fields.offer.value).toBe('Padrao');expect(o.fields.campaign.value).toBe('Copa');expect(o.fields.partner.conflict).toBe(true);expect(o.fields.campaign.conflict).toBe(true);expect(o.fields.segment.value).toBe('Abandonados');});
 it('does not treat 21D as dispatch 21, order zero or midnight as established moment',()=>{const r=row();r.message.payload.activity_name='afz_car_srs_aqs_wpp_car_disp21vibeecred_pontual';const o=orchestrateCommunication(r,[activity({'Activity name / Taxonomia':r.message.payload.activity_name,'Ordem de disparo':0,'Horário de Disparo':'00:00:00'})],[],[]);expect(o.moment.dispatch).toBe(2);expect(o.moment.confidence).toBe('baixa');expect(o.moment.reasons.join(' ')).toMatch(/ambíguo/);expect(o.moment.reasons.join(' ')).toMatch(/Ordem 0/);});
 it('uses scoped manual moment before ID suggestion',()=>{const r=row();const o=orchestrateCommunication(r,[],[{id:'s',journey_name:r.message.payload.journey_name,activity_name:r.message.payload.activity_name,channel:'WhatsApp',metadata:{moment_suggestion:{source:'manual',enabled:true,dispatch:3,week:2,label:'Semana 2 · Disparo 3'}}}],[]);expect(o.moment.dispatch).toBe(3);expect(o.moment.week).toBe(2);expect(o.moment.confidence).toBe('manual');});
 it('keeps wrong carrinho family as a conflict and exposes ID variant and index',()=>{const r=row();r.proposed_template_id='b2c_carsab_vibe_inst_DispD1';const o=orchestrateCommunication(r,[],[],[]);expect(o.fields.family.conflict).toBe(true);expect(o.fields.partner.conflict).toBe(true);expect(o.templateParts).toContainEqual({label:'Variante',value:'Institucional'});expect(o.templateParts).toContainEqual({label:'Índice do template',value:'D1'});});
});
