import { useEffect, useMemo, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { X, Search, RefreshCw, Check, ChevronRight } from 'lucide-react';
import { describeError, listTemplates } from '../../services/communicationService';
import { notifyPackageChanged, readCandidates, readContents } from '../../services/sfmcPackageService';
import { normalizeCommunicationText, proposalGroup, readProposalReuse, reviewProposals, saveProposal, type ProposalReuse, type ProposalRow } from '../../services/communicationProposalService';
import { normalizeJourney } from '../../modules/sfmc-package/parsePackage';
import type { ApplyPreview, CandidateActivity, ReviewDecision, TemplateContent } from '../../modules/sfmc-package/types';
import type { CommunicationTemplate } from '../../types/communication';
import { MessagePreview } from './previews/MessagePreview';
const control='rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm';
const button='rounded-lg bg-cyan-700 px-3 py-2 text-sm font-semibold text-white disabled:opacity-40';
const labels={ready:'Pronta',review:'Revisar',technical:'Técnica',rejected:'Rejeitada',applied:'Aplicada'};
const value=(p:ProposalRow,key:string)=>String(p.resolved_context[key]||'Não identificado');
const localDay=(date:string)=>new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(date));
export function CommunicationProposalInbox({rows,loading,error,onRefresh,onChanged}:{rows:ProposalRow[];loading:boolean;error:string;onRefresh:()=>void;onChanged:()=>void}) {
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('pending'),[channel,setChannel]=useState('');
 const [selected,setSelected]=useState<string[]>([]),[detail,setDetail]=useState<ProposalRow|null>(null),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState(''),[failure,setFailure]=useState('');
 const [simulation,setSimulation]=useState<{result:ApplyPreview&{preview_token:string};rows:ProposalRow[];key:string}|null>(null);
 const [rejecting,setRejecting]=useState(false),[rejectNote,setRejectNote]=useState('');
 const visible=useMemo(()=>rows.filter(p=>(filter==='pending'?['ready','review'].includes(p.status):filter==='all'?true:p.status===filter)&&(!channel||p.message.payload.content.channel===channel)&&(!query||(p.message.payload.activity_name+' '+p.message.payload.journey_name+' '+p.proposed_template_id+' '+JSON.stringify(p.resolved_context)).toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>a.message.payload.journey_name.localeCompare(b.message.payload.journey_name)||a.message.payload.occurrence_key.localeCompare(b.message.payload.occurrence_key)),[rows,filter,channel,query]);
 const chosen=rows.filter(p=>selected.includes(p.id));
 useEffect(()=>{setSimulation(null);setSelected([]);},[rows]);
 const toggle=(p:ProposalRow)=>{setSimulation(null);setFailure('');if(selected.includes(p.id)){setSelected(selected.filter(id=>id!==p.id));return;}if(chosen.length&&proposalGroup(chosen[0])!==proposalGroup(p)){setFailure('O lote deve ter a mesma origem, canal e público. Limpe a seleção para revisar outro grupo.');return;}setSelected([...selected,p.id]);};
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setFailure('');setFeedback('');try{await fn();}catch(e){setFailure(describeError(e));setSimulation(null);}finally{setBusy(false);}};
 const refresh=()=>{setSelected([]);setSimulation(null);setDetail(null);onChanged();notifyPackageChanged();};
 const repeat=(p:ProposalRow)=>{const text=normalizeCommunicationText(p.message.payload.content.body_text);if(!text)return 'Sem texto';const copies=rows.filter(r=>r.id!==p.id&&!r.message.payload.is_optout&&normalizeCommunicationText(r.message.payload.content.body_text)===text);const same=copies.filter(r=>!!p.resolved_context.partner&&!!p.resolved_context.segment&&value(r,'partner')===value(p,'partner')&&value(r,'segment')===value(p,'segment')&&r.message.payload.content.channel===p.message.payload.content.channel);return same.length?`${same.length} uso(s) coletados no mesmo público`:copies.length?`${copies.length} uso(s) em outros públicos`:'Sem repetição no acervo coletado';};
 return <section className="space-y-3" aria-label="Propostas de comunicação">
 <div className="flex flex-wrap items-center gap-2"><div className="relative min-w-60 flex-1"><Search size={15} className="absolute left-3 top-3 text-slate-400"/><input aria-label="Buscar propostas" className={control+' w-full pl-9'} placeholder="Activity Name, ID, parceiro ou jornada" value={query} onChange={e=>setQuery(e.target.value)}/></div>
 <select aria-label="Estado da proposta" className={control} value={filter} onChange={e=>setFilter(e.target.value)}><option value="pending">A revisar</option><option value="ready">Prontas</option><option value="review">Com pendências</option><option value="applied">Aplicadas</option><option value="rejected">Rejeitadas</option><option value="technical">Técnicas / opt-outs</option><option value="all">Todas</option></select>
 <select aria-label="Canal das propostas" className={control} value={channel} onChange={e=>setChannel(e.target.value)}><option value="">Todos os canais</option>{['WhatsApp','SMS','E-mail','Push'].map(c=><option key={c}>{c}</option>)}</select><button aria-label="Atualizar propostas" disabled={busy||loading} onClick={onRefresh} className={control}><RefreshCw size={16}/></button></div>
 <p className="text-xs text-slate-500">{visible.length} comunicações neste filtro · Fila independente do mês dos dashboards. A ordem dos nós não comprova a ordem dos disparos.</p>
 {(error||failure)&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error||failure}</p>}{feedback&&<p role="status" className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-800">{feedback}</p>}
 <div className="flex flex-wrap items-center gap-2 rounded-xl border bg-white p-3"><span className="mr-auto text-sm">{chosen.length} selecionada(s)</span>
 <button className={control} disabled={busy} onClick={()=>{const first=visible.find(p=>p.status==='ready');if(!first)return;setSelected(visible.filter(p=>p.status==='ready'&&proposalGroup(p)===proposalGroup(first)).map(p=>p.id));setSimulation(null);}}>Selecionar grupo pronto do filtro</button>
 <button className={control} disabled={busy||!chosen.length} onClick={()=>{setSelected([]);setSimulation(null);}}>Limpar</button>
 <button className={control} disabled={busy||!chosen.length} onClick={()=>{setRejecting(true);setSimulation(null);}}>Rejeitar seleção</button>
 <button className={control} disabled={busy||!chosen.length||chosen.some(p=>p.status!=='ready')} onClick={()=>void run(async()=>{const frozen=chosen.map(p=>({...p}));const result=await reviewProposals(frozen,'preview');setSimulation({result,rows:frozen,key:crypto.randomUUID()});})}>Simular aprovação</button>
 <button className={button} disabled={busy||!simulation} onClick={()=>void run(async()=>{if(!simulation)return;const result=await reviewProposals(simulation.rows,'apply',simulation.result.preview_token,simulation.key);refresh();setFeedback(`${result.messages} comunicações aprovadas · ${result.activities} disparos vinculados.`);})}>Aprovar seleção</button></div>
 {simulation&&<p role="status" className="rounded-lg bg-cyan-50 p-3 text-sm text-cyan-900">Simulação: {simulation.result.messages} comunicações · {simulation.result.new_templates} novos IDs · {simulation.result.contents} versões novas · {simulation.result.activities} disparos. Versão atual somente nos itens escolhidos explicitamente.</p>}
 {rejecting&&<div className="flex flex-wrap gap-2 rounded-xl border border-red-200 bg-white p-3"><input aria-label="Motivo da rejeição" className={control+' flex-1'} placeholder="Motivo da rejeição" value={rejectNote} onChange={e=>setRejectNote(e.target.value)}/><button className={control} disabled={busy} onClick={()=>setRejecting(false)}>Cancelar</button><button className={button} disabled={busy||rejectNote.trim().length<3||!chosen.length} onClick={()=>void run(async()=>{await reviewProposals(chosen,'reject',null,null,rejectNote);setRejecting(false);setRejectNote('');refresh();setFeedback('Seleção rejeitada; motivo preservado no histórico.');})}>Confirmar rejeição</button></div>}
 <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full text-left text-xs"><thead className="bg-slate-50 text-slate-600"><tr>{['Seleção','Estado / canal','Público / contexto','Jornada / ocorrência','Template observado → proposto','Texto / reuso','Revisão'].map(t=><th key={t} className="px-3 py-3 font-semibold">{t}</th>)}</tr></thead><tbody>{visible.map(p=><tr key={p.id} className={'border-t align-top '+(selected.includes(p.id)?'bg-cyan-50':'hover:bg-slate-50')}><td className="px-3 py-3"><input type="checkbox" aria-label={'Selecionar '+p.message.payload.activity_name} disabled={busy||!['ready','review'].includes(p.status)} checked={selected.includes(p.id)} onChange={()=>toggle(p)}/></td><td className="px-3 py-3"><span className={'rounded-full px-2 py-1 '+(p.status==='ready'?'bg-emerald-50 text-emerald-800':p.status==='review'?'bg-amber-50 text-amber-900':'bg-slate-100')}>{labels[p.status]}</span><p className="mt-2">{p.message.payload.content.channel}</p></td><td className="min-w-32 px-3 py-3"><strong>{value(p,'partner')}</strong><p className="mt-1">{value(p,'segment')} · {value(p,'subgroup')}{p.resolved_context.campaign?' · '+String(p.resolved_context.campaign):''}</p></td><td className="max-w-72 px-3 py-3"><p className="break-all font-medium">{p.message.payload.activity_name||'Sem Activity Name'}</p><p className="mt-1 break-all text-slate-500">{p.message.payload.journey_name} · v{p.message.payload.journey_version}</p><p className="mt-1 text-slate-500">{p.review.start_date?`${p.review.start_date} → ${p.review.end_date}`:'Período histórico não confirmado'} · {p.review.activity_ids.length} alvo(s)</p></td><td className="min-w-52 px-3 py-3"><p className="break-all font-mono text-slate-500">{p.observed_template_id||'Sem af_sub3 no link'}</p><p className="mt-1 break-all font-mono font-semibold text-slate-900">→ {p.proposed_template_id||'ID a definir'}</p>{p.conflicts.length>0&&<p className="mt-1 text-amber-800">{p.conflicts.length} divergência(s) registrada(s)</p>}</td><td className="max-w-64 px-3 py-3"><p className="line-clamp-2">{normalizeCommunicationText(p.message.payload.content.body_text)||'Texto não extraído'}</p><p className="mt-1 text-cyan-800">{repeat(p)}</p></td><td className="px-3 py-3"><button className={control+' inline-flex items-center gap-1 whitespace-nowrap'} onClick={()=>{setDetail(p);setSimulation(null);}}>Revisar <ChevronRight size={14}/></button></td></tr>)}</tbody></table>
 {loading&&<p role="status" className="p-6 text-center text-sm">Carregando propostas…</p>}{!loading&&!visible.length&&<p className="p-8 text-center text-sm text-slate-500">Nenhuma proposta neste filtro. Análises recebidas aparecem aqui para revisão.</p>}</div>
 {detail&&<ProposalDetail row={detail} onClose={()=>setDetail(null)} onSaved={()=>{setDetail(null);refresh();}}/>}
 </section>;
}
function ProposalDetail({row,onClose,onSaved}:{row:ProposalRow;onClose:()=>void;onSaved:()=>void}) {
 const [review,setReview]=useState<ReviewDecision>({...row.review}),[note,setNote]=useState(''),[resolved,setResolved]=useState(row.status==='ready');
 const [acts,setActs]=useState<CandidateActivity[]>([]),[versions,setVersions]=useState<TemplateContent[]>([]),[catalog,setCatalog]=useState<CommunicationTemplate[]>([]);
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[reuse,setReuse]=useState<ProposalReuse|null>(null);
 const root=useRef<HTMLDivElement>(null);const pending=['ready','review'].includes(row.status);
 useEffect(()=>{let active=true;Promise.all([readCandidates(row.message.import_id),readContents(),listTemplates(),readProposalReuse(row.id)]).then(([a,v,c,r])=>{if(active){setActs(a);setVersions(v);setCatalog(c);setReuse(r);setLoaded(true);}}).catch(e=>{if(active)setError(describeError(e));});return()=>{active=false;};},[row.message.import_id]);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;document.body.style.overflow='hidden';root.current?.querySelector<HTMLButtonElement>('button')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const nodes=Array.from(root.current?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),textarea:not([disabled])')||[]),first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key);previous?.focus();};},[onClose]);
 const p=row.message.payload,current=versions.find(v=>v.template_id===review.template_id&&v.is_current);
 const exact=acts.filter(a=>a.activity_name===p.activity_name&&a.channel===p.content.channel&&normalizeJourney(a.journey_name)===normalizeJourney(p.journey_name));
 const eligible=exact.filter(a=>review.start_date&&review.end_date&&localDay(a.dispatch_date)>=review.start_date&&localDay(a.dispatch_date)<=review.end_date&&(!a.template_id||a.template_id===review.template_id));
 const set=(patch:Partial<ReviewDecision>)=>setReview(previous=>({...previous,...patch}));
 return createPortal(<div className="fixed inset-0 z-[100] flex justify-end bg-slate-950/40"><div ref={root} role="dialog" aria-modal="true" aria-labelledby="proposal-title" className="flex h-full w-full max-w-4xl flex-col bg-white shadow-2xl"><header className="flex items-center justify-between border-b px-5 py-4"><div><h2 id="proposal-title" className="font-semibold">Revisar comunicação</h2><p className="text-xs text-slate-500">Revisão {row.revision} · {labels[row.status]}</p></div><button aria-label="Fechar revisão" onClick={onClose} className={control}><X size={18}/></button></header>
 <div className="flex-1 overflow-y-auto p-5"><p className="break-all text-sm font-semibold">{p.activity_name}</p><p className="mt-1 break-all text-xs text-slate-500">{p.journey_name} · {p.content.channel} · {row.message.import_id}</p>
 <div className="mt-4 grid gap-5 md:grid-cols-[minmax(0,1fr)_300px]"><div className="space-y-4"><div className="rounded-lg bg-slate-50 p-3 text-sm"><strong>{value(row,'partner')} · {value(row,'segment')} · {value(row,'subgroup')}{row.resolved_context.campaign?' · '+String(row.resolved_context.campaign):''}</strong><p className="mt-1 text-xs">{value(row,'order')}</p>{p.paths.map((path,i)=><p key={i} className="mt-2 text-xs">{path.labels.join(' → ')}{path.waits.length?' · Esperas: '+path.waits.join(' + '):''}</p>)}</div>
 <div className="space-y-1 text-xs">{row.reasons.map((r,i)=><p key={'r'+i} className="text-cyan-800">{r}</p>)}{row.conflicts.map((c,i)=><p key={'c'+i} className="rounded bg-amber-50 p-2 text-amber-900">{c}</p>)}<p>Alternativas: {row.alternatives.join(', ')||'Nenhuma registrada'}</p><p>ID observado: <span className="font-mono">{row.observed_template_id||'Não disponível'}</span></p></div>
 <label className="block text-sm font-medium">Template ID proposto<input aria-label="Template ID proposto" list="proposal-catalog" className={control+' mt-1 w-full font-mono'} disabled={!pending||busy} value={review.template_id} onChange={e=>{set({template_id:e.target.value.trim(),activity_ids:[],set_current:false});setResolved(false);}}/></label><datalist id="proposal-catalog">{catalog.map(t=><option key={t.template_id} value={t.template_id}>{t.title}</option>)}</datalist>
 <p className="text-xs text-slate-500">O ID preserva a caixa. A sugestão contextual não altera o link extraído nem comprova que a peça foi enviada.</p>
 <label className="flex items-start gap-2 text-sm"><input type="checkbox" disabled={!pending||busy||!loaded} checked={review.set_current} onChange={e=>set({set_current:e.target.checked,expected_current_id:current?.id||null})}/>Escolher este texto como versão atual</label>
 {current&&<details><summary className="cursor-pointer text-xs text-cyan-800">Comparar com o texto atual</summary><MessagePreview content={current.payload} compact/></details>}
 <section className="space-y-2 rounded-lg border p-3"><h3 className="text-sm font-semibold">Vínculos históricos opcionais</h3><p className="text-xs text-slate-500">Sem seleção de disparos, a aprovação registra somente conteúdo e uso configurado.</p><div className="flex flex-wrap gap-2"><label className="text-xs">Início<input aria-label="Início comprovado" type="date" className={control+' block w-full'} disabled={!pending||busy} value={review.start_date||''} onChange={e=>set({start_date:e.target.value||null,activity_ids:[]})}/></label><label className="text-xs">Fim<input aria-label="Fim comprovado" type="date" className={control+' block w-full'} disabled={!pending||busy} value={review.end_date||''} onChange={e=>set({end_date:e.target.value||null,activity_ids:[]})}/></label></div><label className="block text-xs">Evidência do período<input aria-label="Evidência do período" className={control+' mt-1 w-full'} disabled={!pending||busy} value={review.evidence} onChange={e=>set({evidence:e.target.value,activity_ids:[]})}/></label>
 {!loaded&&<p className="text-xs">Consultando execuções e versões…</p>}{loaded&&<p className="text-xs">{exact.length} execuções da mesma jornada/canal · {eligible.length} elegíveis no período escolhido.</p>}
 {eligible.map(a=><label key={a.id} className="flex items-start gap-2 text-xs"><input type="checkbox" disabled={!pending||busy||!review.evidence.trim()} checked={review.activity_ids.includes(a.id)} onChange={e=>set({activity_ids:e.target.checked?[...review.activity_ids,a.id]:review.activity_ids.filter(id=>id!==a.id)})}/>{localDay(a.dispatch_date)} · {a.id} {a.template_id?'(já vinculado ao mesmo ID)':''}</label>)}
 {exact.some(a=>a.template_id&&a.template_id!==review.template_id)&&<p className="text-xs text-amber-800">Existem vínculos com outro ID; eles serão preservados.</p>}</section>
 {pending&&<><label className="block text-sm">Motivo da revisão<textarea aria-label="Motivo da revisão" className={control+' mt-1 w-full'} value={note} disabled={busy} onChange={e=>setNote(e.target.value)} placeholder="Confirme a proposta ou explique a correção e o reuso intencional"/></label><label className="flex items-start gap-2 text-sm"><input type="checkbox" disabled={busy} checked={resolved} onChange={e=>setResolved(e.target.checked)}/>Revisei o ID, o conteúdo e o público; as divergências foram resolvidas para esta aprovação</label></>}
 <section className="rounded-lg border p-3 text-xs"><h3 className="font-semibold">Reuso de texto no acervo aprovado</h3>{reuse?<><p className="mt-1 text-slate-500">Cobertura: {reuse.coverage.approved_versions} versões com texto · {reuse.coverage.linked_activities} execuções com template. Comparação exata do texto normalizado.</p>{reuse.matches.map(r=><p key={r.content_id} className="mt-2 break-all"><strong className="font-mono">{r.template_id}</strong> · {r.linked_activities} execuções vinculadas ao ID · {r.same_context_activities} no mesmo parceiro/segmento · última data {r.last_dispatch?localDay(r.last_dispatch):'não comprovada'}</p>)}{!reuse.matches.length&&<p className="mt-2">Nenhum texto equivalente no acervo aprovado consultado. Histórico sem texto fica fora desta comparação.</p>}<p className="mt-2 text-slate-500">Vínculo ao ID não certifica qual versão foi enviada. Reuso pode ser intencional; não mede repetição por pessoa.</p></>:<p className="mt-1">Consulta ainda não disponível.</p>}</section>
 <details className="text-xs"><summary className="cursor-pointer text-cyan-800">Fonte e atribuição</summary><p className="mt-2 break-all">{p.link_url||'Sem link extraído'}</p><pre className="whitespace-pre-wrap">{JSON.stringify({utm:p.utm,context:row.resolved_context,analysis_id:row.analysis_id},null,2)}</pre></details>
 </div><div><MessagePreview content={p.content} compact/><p className="mt-2 text-xs text-slate-500">Prévia do conteúdo configurado no pacote; não certifica envio histórico.</p></div></div></div>
 <footer className="space-y-2 border-t p-4">{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<div className="flex justify-end gap-2"><button className={control} onClick={onClose}>Fechar</button>{pending&&<button className={button+' inline-flex items-center gap-2'} disabled={busy||!loaded||!review.template_id||(resolved&&note.trim().length<3)} onClick={async()=>{setBusy(true);setError('');try{await saveProposal(row,{...review,expected_current_id:current?.id||null},resolved,note);onSaved();}catch(e){setError(describeError(e));}finally{setBusy(false);}}}><Check size={16}/>Salvar revisão</button>}</div></footer></div></div>,document.body);
}
