import {useEffect,useMemo,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {usePeriod} from '../../contexts/PeriodContext';
import {PeriodSelector} from '../period-selector/PeriodSelector';
import {X,Search,RefreshCw,Check,SlidersHorizontal,Send,Info} from 'lucide-react';
import {describeError,listTemplates} from '../../services/communicationService';
import {notifyPackageChanged,readCandidates,readContents} from '../../services/sfmcPackageService';
import {normalizeCommunicationText,proposalGroup,readProposalReuse,reviewProposals,saveProposal,type ProposalReuse,type ProposalRow} from '../../services/communicationProposalService';
import {readOrchestrationEvidence} from '../../services/communicationOrchestrationService';
import {normalizeJourney} from '../../modules/sfmc-package/parsePackage';
import type {ApplyPreview,CandidateActivity,ReviewDecision,TemplateContent} from '../../modules/sfmc-package/types';
import type {CommunicationTemplate} from '../../types/communication';
import {MessagePreview} from './previews/MessagePreview';
import {ReconciliationProposalRow,STATUS_LABEL} from './ReconciliationProposalRow';
import {ActivityMomentModal} from './ActivityMomentModal';
import {orchestrateCommunication,dispatchDay,missingGovernanceParameters,type FrameworkActivity,type OrchestrationSlot} from '../../utils/communicationOrchestrator';
import {parseActivity,canalToId} from '../../utils/taxonomy';
import type {CatalogEntry,OrphanRow} from '../../hooks/useReconciliation';
import {HowItWorks,Segmented,controlClass} from './ui/commsUi';
const control='rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm font-semibold text-slate-700 disabled:opacity-50';
const button='rounded-lg bg-cyan-700 px-4 py-2 text-sm font-bold text-white hover:bg-cyan-800 disabled:opacity-50';
const labels=STATUS_LABEL;
const value=(p:ProposalRow,key:string)=>String(p.resolved_context[key]||'Não identificado');
const localDay=dispatchDay;
const mainFilters=[['front','Frente / BU'],['segment','Segmento']] as const;
const moreFilters=[['partner','Parceiro / origem'],['channel','Canal'],['subgroup','Subgrupo'],['campaign','Campanha'],['offer','Oferta'],['week','Semana'],['dispatch','Dia / disparo']] as const;
type Lane='governed'|'warnings'|'technical';
type StatusFilter='pending'|'ready'|'review'|'missing'|'applied'|'rejected'|'all';
export interface InboxSummary {pending:number;ready:number;review:number;applied:number;hidden:number}
const laneOf=(p:ProposalRow):Lane=>p.message.payload.is_optout?'technical':missingGovernanceParameters(p).length===0?'governed':'warnings';
export const INBOX_STEPS=[
 {title:'Revisar',text:'Confira o ID proposto, a prévia da mensagem e as etiquetas. Abra os detalhes para ver as fontes e as divergências.'},
 {title:'Aprovar',text:'Selecione um grupo com a mesma origem, canal e público e clique em Aprovar. Você vê o que vai mudar antes de gravar.'},
 {title:'Enviar',text:'Enviar grava os vínculos e o texto no GaaS. Nenhuma mensagem é disparada para clientes.'},
];
export const INBOX_GLOSSARY=[
 {term:'Template ID',text:'o código da peça, igual ao af_sub3 do link. A caixa das letras é preservada.'},
 {term:'Com ID no link',text:'o link do disparo já traz o ID e os parâmetros c, af_sub1, af_sub2 e af_sub3.'},
 {term:'Sem ID no link',text:'o link não traz o ID; a análise propõe um, que deve ser conferido um a um.'},
 {term:'Opt-out',text:'a resposta automática de quem pediu para não receber mais. Fica fora dos lotes.'},
 {term:'Divergência',text:'as fontes (link, Activity Name, Framework) dizem coisas diferentes sobre a mesma etiqueta.'},
 {term:'Período',text:'a fila mostra só comunicações com disparo no período do calendário.'},
];
export function CommunicationProposalInbox({rows,loading,error,onRefresh,onChanged,onSummary,catalog=[]}:{catalog?:CatalogEntry[];rows:ProposalRow[];loading:boolean;error:string;onRefresh:()=>void;onChanged:()=>void;onSummary?:(s:InboxSummary)=>void}) {
 const [query,setQuery]=useState(''),[filter,setFilter]=useState<StatusFilter>('pending'),[contextFilters,setContextFilters]=useState<Record<string,string>>({});
 const [sort,setSort]=useState('priority'),[direction,setDirection]=useState(-1),[page,setPage]=useState(1),[expanded,setExpanded]=useState<string|null>(null),[showMore,setShowMore]=useState(false);
 const {startDate,endDate}=usePeriod();
 const start=dispatchDay(startDate.toISOString()),end=dispatchDay(endDate.toISOString());
 const [lane,setLane]=useState<Lane>('governed');
 const [selected,setSelected]=useState<string[]>([]),[detail,setDetail]=useState<{row:ProposalRow;id?:string}|null>(null),[momentRow,setMomentRow]=useState<OrphanRow|null>(null),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState(''),[failure,setFailure]=useState('');
 const [simulation,setSimulation]=useState<{result:ApplyPreview&{preview_token:string};rows:ProposalRow[];key:string}|null>(null);
 const [rejecting,setRejecting]=useState(false),[rejectNote,setRejectNote]=useState('');
 const [evidence,setEvidence]=useState<{activities:FrameworkActivity[];slots:OrchestrationSlot[]}>({activities:[],slots:[]}),[evidenceLoading,setEvidenceLoading]=useState(true),[evidenceError,setEvidenceError]=useState('');
 useEffect(()=>{let active=true;setEvidenceLoading(true);setEvidenceError('');setEvidence({activities:[],slots:[]});readOrchestrationEvidence(rows).then(data=>{if(active)setEvidence(data);}).catch(e=>{if(active)setEvidenceError(describeError(e));}).finally(()=>{if(active)setEvidenceLoading(false);});return()=>{active=false;};},[rows]);
 const invalidPeriod=!!(start&&end&&start>end),partialPeriod=!!start!==!!end;
 const periodOk=!!(start&&end&&!invalidPeriod&&!partialPeriod);
 const orchestrations=useMemo(()=>new Map(rows.map(p=>[p.id,orchestrateCommunication(p,evidence.activities,evidence.slots,catalog,periodOk?{start,end}:null)])),[rows,evidence,catalog,start,end,periodOk]);
 const fieldValue=(p:ProposalRow,key:string)=>{const o=orchestrations.get(p.id)!;return key==='week'?String(o.moment.week??'Não identificado'):key==='dispatch'?String(o.moment.dispatch??'Não identificado'):o.fields[key]?.value||'Não identificado';};
 const statusFor=(p:ProposalRow)=>p.status==='ready'&&orchestrations.get(p.id)!.conflicts.length&&!p.reviewed_by?'review':p.status;
 // Só entra na fila o que teve disparo no período do calendário: métricas e IDs propostos seguem o mesmo recorte.
 const inPeriod=useMemo(()=>periodOk&&!evidenceLoading?rows.filter(p=>(orchestrations.get(p.id)?.exec||0)>0):[],[rows,orchestrations,periodOk,evidenceLoading]);
 const hidden=periodOk&&!evidenceLoading?rows.length-inPeriod.length:0;
 const laneRows=useMemo(()=>inPeriod.filter(p=>laneOf(p)===lane),[inPeriod,lane]);
 const matchesStatus=(p:ProposalRow,key:StatusFilter)=>key==='pending'?['ready','review'].includes(p.status):key==='missing'?!p.proposed_template_id&&!p.message.payload.is_optout:key==='all'?true:statusFor(p)===key;
 useEffect(()=>{if(!onSummary)return;onSummary({pending:inPeriod.filter(p=>['ready','review'].includes(p.status)).length,ready:inPeriod.filter(p=>statusFor(p)==='ready').length,review:inPeriod.filter(p=>statusFor(p)==='review').length,applied:inPeriod.filter(p=>p.status==='applied').length,hidden});},[inPeriod,hidden,onSummary,orchestrations]);
 const visible=useMemo(()=>laneRows.filter(p=>matchesStatus(p,filter)&&Object.entries(contextFilters).every(([key,v])=>!v||fieldValue(p,key)===v)&&(!query||(p.message.payload.activity_name+' '+p.message.payload.journey_name+' '+p.proposed_template_id+' '+JSON.stringify(orchestrations.get(p.id)?.fields)).toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>{
  const ao=orchestrations.get(a.id)!,bo=orchestrations.get(b.id)!;
  const av=sort==='base'?ao.base:sort==='exec'?(ao.exec||null):sort==='recent'?ao.latest:sort==='order'?(ao.moment.dispatch==null?null:(ao.moment.week||0)*1000+ao.moment.dispatch):a.conflicts.length+ao.conflicts.length+(a.status==='review'?1:0);
  const bv=sort==='base'?bo.base:sort==='exec'?(bo.exec||null):sort==='recent'?bo.latest:sort==='order'?(bo.moment.dispatch==null?null:(bo.moment.week||0)*1000+bo.moment.dispatch):b.conflicts.length+bo.conflicts.length+(b.status==='review'?1:0);
  if(av==null&&bv!=null)return 1;if(bv==null&&av!=null)return -1;
  const cmp=typeof av==='number'&&typeof bv==='number'?av-bv:String(av??'').localeCompare(String(bv??''));
  return cmp*direction||a.id.localeCompare(b.id);
 }),[laneRows,filter,contextFilters,query,orchestrations,sort,direction]);
 useEffect(()=>{setPage(1);setSelected([]);setSimulation(null);},[query,filter,contextFilters,sort,direction,start,end,rows,lane]);
 const ready=!evidenceLoading&&!evidenceError&&periodOk;
 const pageRows=ready?visible.slice((page-1)*25,page*25):[];
 const chosen=rows.filter(p=>selected.includes(p.id));
 const eligible=(p:ProposalRow)=>missingGovernanceParameters(p).length===0&&p.status==='ready'&&['front','partner','segment','channel'].every(key=>fieldValue(p,key)!=='Não identificado')&&!evidenceLoading&&!evidenceError&&(!orchestrations.get(p.id)!.conflicts.length||!!p.reviewed_by);
 const toggle=(p:ProposalRow)=>{setSimulation(null);setFailure('');if(selected.includes(p.id)){setSelected(selected.filter(id=>id!==p.id));return;}if(chosen.length&&proposalGroup(chosen[0])!==proposalGroup(p)){setFailure('O lote precisa ter a mesma origem, canal e público. Limpe a seleção para montar outro grupo.');return;}setSelected([...selected,p.id]);};
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);setFailure('');setFeedback('');try{await fn();}catch(e){setFailure(describeError(e));setSimulation(null);}finally{setBusy(false);}};
 const refresh=()=>{setSelected([]);setSimulation(null);setDetail(null);onChanged();notifyPackageChanged();};
 const repeat=(p:ProposalRow)=>{const text=normalizeCommunicationText(p.message.payload.content.body_text);if(!text)return 'Sem texto para comparar reuso';const copies=rows.filter(r=>r.id!==p.id&&!r.message.payload.is_optout&&normalizeCommunicationText(r.message.payload.content.body_text)===text);const known=(r:ProposalRow)=>['partner','segment','channel'].every(k=>fieldValue(r,k)!=='Não identificado');const same=copies.filter(r=>known(p)&&known(r)&&['partner','segment','channel'].every(k=>fieldValue(r,k)===fieldValue(p,k)));return same.length?`${same.length} outra(s) comunicação(ões) com o mesmo texto e o mesmo público`:copies.length?`${copies.length} outra(s) comunicação(ões) com o mesmo texto em outro contexto`:'Nenhum texto igual entre as comunicações recebidas; isso não prova que nunca foi usado';};
 const editMoment=(p:ProposalRow)=>{const o=orchestrations.get(p.id)!;setMomentRow({uid:p.id,name:p.message.payload.activity_name,jornada:p.message.payload.journey_name,channel:canalToId(p.message.payload.content.channel),canalLabel:p.message.payload.content.channel,segmentoLabel:o.fields.segment.value,subgrupoLabel:o.fields.subgroup.value,base:o.base||0,exec:o.exec,latestDate:o.latest,parsed:parseActivity(p.message.payload.activity_name,{jornada:p.message.payload.journey_name,canal:p.message.payload.content.channel}),match:null,confidence:'fraca',suggestedId:p.proposed_template_id,momentConflict:!!o.moment.alternatives.length,momentSuggestion:{kind:o.moment.week?'semana_disparo':'disparo',enabled:o.moment.dispatch!=null,week:o.moment.week,dispatch:o.moment.dispatch,label:o.moment.label,confidence:o.moment.confidence==='manual'?'manual':o.moment.confidence==='média'?'media':'baixa',source:o.moment.confidence==='manual'?'manual':'parser'}});};
 const laneCount=(key:Lane)=>inPeriod.filter(p=>laneOf(p)===key).length;
 const activeMore=moreFilters.filter(([key])=>contextFilters[key]).length;
 const optionsFor=(key:string)=>[...new Set(laneRows.map(p=>fieldValue(p,key)))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));
 const selectFilter=([key,label]:readonly [string,string])=><label key={key} className="flex flex-col gap-1 text-xs font-semibold text-slate-600">{label}<select className={controlClass} value={contextFilters[key]||''} onChange={e=>setContextFilters({...contextFilters,[key]:e.target.value})}><option value="">Todos</option>{optionsFor(key).map(v=><option key={v}>{v}</option>)}</select></label>;
 return <section className="space-y-4" aria-label="Fila de comunicações para revisar">
  <HowItWorks steps={INBOX_STEPS} glossary={INBOX_GLOSSARY}/>
  <div className="flex flex-wrap items-center gap-3">
   <Segmented<Lane> label="Tipo de link" value={lane} onChange={v=>{setLane(v);setFilter(v==='technical'?'all':'pending');}} options={[{id:'governed',label:'Com ID no link',count:laneCount('governed')},{id:'warnings',label:'Sem ID no link',count:laneCount('warnings')},{id:'technical',label:'Opt-outs',count:laneCount('technical')}]}/>
   {lane!=='technical'&&<Segmented<StatusFilter> label="Situação" value={filter} onChange={setFilter} options={([['pending','A revisar'],['ready','Prontas'],['missing','Sem ID proposto'],['applied','Enviadas'],['rejected','Rejeitadas'],['all','Todas']] as [StatusFilter,string][]).map(([id,label])=>({id,label,count:laneRows.filter(p=>matchesStatus(p,id)).length}))}/>}
  </div>
  {lane==='warnings'&&<p className="flex gap-2 rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900"><Info size={16} aria-hidden="true" className="mt-0.5 shrink-0"/>O link destas comunicações não traz o ID do template (af_sub3) nem todos os parâmetros. O ID e as etiquetas são uma proposta da análise: revise um a um. Elas não entram na aprovação em lote.</p>}
  {lane==='technical'&&<p className="flex gap-2 rounded-lg border border-slate-200 bg-slate-50 p-3 text-sm text-slate-700"><Info size={16} aria-hidden="true" className="mt-0.5 shrink-0"/>Respostas automáticas de opt-out. Ficam aqui para consulta e não viram template de campanha.</p>}
  <div className="flex flex-wrap items-end gap-3 rounded-xl border border-slate-200 bg-white p-3">
   <div className="flex flex-col gap-1 text-xs font-semibold text-slate-600">Período<PeriodSelector compact/></div>
   {mainFilters.map(selectFilter)}
   <label className="flex min-w-56 flex-1 flex-col gap-1 text-xs font-semibold text-slate-600">Buscar<span className="relative"><Search size={14} aria-hidden="true" className="absolute left-3 top-3 text-slate-600"/><input className={controlClass+' w-full pl-9'} placeholder="ID, etiqueta, jornada ou Activity Name" value={query} onChange={e=>setQuery(e.target.value)}/></span></label>
   <label className="flex flex-col gap-1 text-xs font-semibold text-slate-600">Ordenar por<select className={controlClass} value={sort+':'+direction} onChange={e=>{const [s,d]=e.target.value.split(':');setSort(s);setDirection(Number(d));}}><option value="priority:-1">Prioridade</option><option value="base:-1">Maior base</option><option value="exec:-1">Mais execuções</option><option value="recent:-1">Mais recentes</option><option value="order:1">Ordem da régua</option></select></label>
   <button type="button" aria-expanded={showMore} onClick={()=>setShowMore(!showMore)} className={control+' inline-flex items-center gap-2'}><SlidersHorizontal size={15} aria-hidden="true"/>Mais filtros{activeMore>0&&<span className="rounded-full bg-cyan-700 px-1.5 text-xs text-white">{activeMore}</span>}</button>
   <button aria-label="Atualizar a fila" title="Atualizar a fila" disabled={busy||loading} onClick={onRefresh} className={control}><RefreshCw size={15} aria-hidden="true"/></button>
   {showMore&&<div className="flex w-full flex-wrap items-end gap-3 border-t border-slate-200 pt-3">{moreFilters.map(selectFilter)}{Object.values(contextFilters).some(Boolean)&&<button type="button" onClick={()=>setContextFilters({})} className="text-sm font-semibold text-cyan-800 underline">Limpar filtros</button>}</div>}
  </div>
  <p className="text-sm text-slate-600" aria-live="polite">{ready?`${visible.length} ${visible.length===1?'comunicação':'comunicações'} com disparo no período.`:''}{ready&&hidden>0?` ${hidden} sem disparo neste período ficam ocultas; mude o período no calendário para ver outros meses.`:''}</p>
  {(error||failure||evidenceError)&&<p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error||failure||evidenceError}</p>}{feedback&&<p role="status" className="rounded-lg bg-emerald-50 p-3 text-sm text-emerald-900">{feedback}</p>}
  {(loading||evidenceLoading)&&<p role="status" className="text-sm text-slate-600">Consultando disparos, catálogo e propostas…</p>}
  {(invalidPeriod||partialPeriod)&&<p role="alert" className="text-sm text-amber-900">Revise o período: a data inicial precisa vir antes da final.</p>}
  {lane!=='technical'&&ready&&<div className="flex flex-wrap items-center gap-2"><button className={control} disabled={busy||!visible.some(eligible)} onClick={()=>{const first=visible.find(eligible);if(first)setSelected(visible.filter(p=>eligible(p)&&proposalGroup(p)===proposalGroup(first)).map(p=>p.id));setSimulation(null);}}>Selecionar grupo pronto</button><span className="text-xs text-slate-600">Seleciona as prontas com a mesma origem, canal e público.</span></div>}
  {chosen.length>0&&<div className="space-y-3 rounded-xl border border-cyan-300 bg-cyan-50 p-4">
   <div className="flex flex-wrap items-center gap-2"><span className="mr-auto text-sm font-semibold text-cyan-950">{chosen.length} {chosen.length===1?'selecionada':'selecionadas'}</span><button className={control} disabled={busy} onClick={()=>{setSelected([]);setSimulation(null);}}>Limpar</button><button className={control} disabled={busy} onClick={()=>{setRejecting(true);setSimulation(null);}}>Rejeitar</button>
    {!simulation?<button className={button+' inline-flex items-center gap-2'} disabled={busy||chosen.some(p=>!eligible(p))} onClick={()=>void run(async()=>{const frozen=chosen.map(p=>({...p}));const result=await reviewProposals(frozen,'preview');setSimulation({result,rows:frozen,key:crypto.randomUUID()});})}><Check size={16} aria-hidden="true"/>Aprovar</button>
    :<button className={button+' inline-flex items-center gap-2'} disabled={busy} onClick={()=>void run(async()=>{const result=await reviewProposals(simulation.rows,'apply',simulation.result.preview_token,simulation.key);refresh();setFeedback(`${result.messages} ${result.messages===1?'comunicação enviada':'comunicações enviadas'} · ${result.activities} disparos vinculados.`);})}><Send size={16} aria-hidden="true"/>Enviar</button>}</div>
   {chosen.some(p=>!eligible(p))&&<p className="text-sm text-amber-900">Há itens com pendência ou sem ID no link. Revise um a um antes de aprovar em lote.</p>}
   {simulation&&<p role="status" className="text-sm text-cyan-950">Aprovado. Ao enviar: {simulation.result.messages} comunicações · {simulation.result.new_templates} IDs novos · {simulation.result.contents} versões de texto · {simulation.result.activities} disparos vinculados. Enviar grava no GaaS; nenhuma mensagem é disparada.</p>}
  </div>}
  {rejecting&&<div className="flex flex-wrap gap-2 rounded-xl border border-red-300 bg-white p-3"><input aria-label="Motivo da rejeição" className={controlClass+' flex-1'} placeholder="Motivo da rejeição" value={rejectNote} onChange={e=>setRejectNote(e.target.value)}/><button className={control} disabled={busy} onClick={()=>setRejecting(false)}>Cancelar</button><button className={button} disabled={busy||rejectNote.trim().length<3||!chosen.length} onClick={()=>void run(async()=>{await reviewProposals(chosen,'reject',null,null,rejectNote);setRejecting(false);setRejectNote('');refresh();setFeedback('Seleção rejeitada; o motivo fica na Auditoria.');})}>Confirmar rejeição</button></div>}
  <div className="flex flex-col gap-2">{pageRows.map(p=><ReconciliationProposalRow key={p.id} template={catalog.find(t=>t.id===p.proposed_template_id)?.raw} row={p} o={orchestrations.get(p.id)!} open={expanded===p.id} checked={selected.includes(p.id)} busy={busy} onToggle={()=>setExpanded(expanded===p.id?null:p.id)} onSelect={()=>toggle(p)} onReview={id=>{setDetail({row:p,id});setSimulation(null);}} onMoment={()=>editMoment(p)} reuse={repeat(p)}/>)}{ready&&!loading&&!pageRows.length&&<p className="rounded-xl border border-slate-200 bg-white p-6 text-sm text-slate-600">{inPeriod.length?'Nenhuma comunicação neste filtro. Limpe os filtros ou escolha outra situação.':'Nenhuma comunicação com disparo neste período. Escolha outro período no calendário para revisar meses anteriores.'}</p>}</div>
  {ready&&visible.length>25&&<div className="flex items-center justify-end gap-3 text-sm"><button className={control} disabled={page===1} onClick={()=>setPage(page-1)}>Anterior</button><span>Página {page} de {Math.max(1,Math.ceil(visible.length/25))}</span><button className={control} disabled={page*25>=visible.length} onClick={()=>setPage(page+1)}>Próxima</button></div>}
  {detail&&<ProposalDetail row={detail.row} initialId={detail.id} onClose={()=>setDetail(null)} onSaved={()=>{setDetail(null);refresh();}}/>}
  {momentRow&&<ActivityMomentModal calendarMoment={/\bDia\b/.test(orchestrations.get(momentRow.uid)?.moment.label||'')} baseKnown={orchestrations.get(momentRow.uid)?.base!=null} row={momentRow} onClose={()=>setMomentRow(null)} onChanged={()=>{setMomentRow(null);refresh();}}/>}
 </section>;
}
function ProposalDetail({row,onClose,onSaved,initialId}:{row:ProposalRow;onClose:()=>void;onSaved:()=>void;initialId?:string}) {
 const [review,setReview]=useState<ReviewDecision>({...row.review,...(initialId?{template_id:initialId,activity_ids:[],set_current:false,expected_current_id:null}: {})}),[note,setNote]=useState(''),[resolved,setResolved]=useState(row.status==='ready'&&!initialId);
 const [acts,setActs]=useState<CandidateActivity[]>([]),[versions,setVersions]=useState<TemplateContent[]>([]),[catalog,setCatalog]=useState<CommunicationTemplate[]>([]);
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(false),[reuse,setReuse]=useState<ProposalReuse|null>(null);
 const root=useRef<HTMLDivElement>(null);const pending=['ready','review'].includes(row.status);
 useEffect(()=>{let active=true;Promise.all([readCandidates(row.message.import_id),readContents(),listTemplates(),readProposalReuse(row.id)]).then(([a,v,c,r])=>{if(active){setActs(a);setVersions(v);setCatalog(c);setReuse(r);setLoaded(true);}}).catch(e=>{if(active)setError(describeError(e));});return()=>{active=false;};},[row.message.import_id]);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null,overflow=document.body.style.overflow;document.body.style.overflow='hidden';root.current?.querySelector<HTMLButtonElement>('button')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'){const nodes=Array.from(root.current?.querySelectorAll<HTMLElement>('button:not([disabled]),input:not([disabled]),textarea:not([disabled])')||[]),first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=overflow;document.removeEventListener('keydown',key);previous?.focus();};},[onClose]);
 const p=row.message.payload,current=versions.find(v=>v.template_id===review.template_id&&v.is_current);
 const exact=acts.filter(a=>a.activity_name===p.activity_name&&a.channel===p.content.channel&&normalizeJourney(a.journey_name)===normalizeJourney(p.journey_name));
 const eligible=exact.filter(a=>review.start_date&&review.end_date&&localDay(a.dispatch_date)>=review.start_date&&localDay(a.dispatch_date)<=review.end_date&&(!a.template_id||a.template_id===review.template_id));
 const set=(patch:Partial<ReviewDecision>)=>setReview(previous=>({...previous,...patch}));
 return createPortal(<div className="fixed inset-0 z-[100] flex justify-end bg-slate-950/40"><div ref={root} role="dialog" aria-modal="true" aria-labelledby="proposal-title" className="flex h-full w-full max-w-4xl flex-col bg-white shadow-2xl"><header className="flex items-center justify-between border-b px-5 py-4"><div><h2 id="proposal-title" className="font-semibold">Revisar comunicação</h2><p className="text-xs text-slate-600">Revisão {row.revision} · {labels[row.status]}</p></div><button aria-label="Fechar revisão" onClick={onClose} className={control}><X size={18}/></button></header>
 <div className="flex-1 overflow-y-auto p-5"><p className="break-all text-sm font-semibold">{p.activity_name}</p><p className="mt-1 break-all text-xs text-slate-600">{p.journey_name} · {p.content.channel} · {row.message.import_id}</p>
 <div className="mt-4 grid gap-5 md:grid-cols-[minmax(0,1fr)_300px]"><div className="space-y-4"><div className="rounded-lg bg-slate-50 p-3 text-sm"><strong>{value(row,'partner')} · {value(row,'segment')} · {value(row,'subgroup')}{row.resolved_context.campaign?' · '+String(row.resolved_context.campaign):''}</strong><p className="mt-1 text-xs">{value(row,'order')}</p>{p.paths.map((path,i)=><p key={i} className="mt-2 text-xs">{path.labels.join(' → ')}{path.waits.length?' · Esperas: '+path.waits.join(' + '):''}</p>)}</div>
 <div className="space-y-1 text-xs">{row.reasons.map((r,i)=><p key={'r'+i} className="text-cyan-800">{r}</p>)}{row.conflicts.map((c,i)=><p key={'c'+i} className="rounded bg-amber-50 p-2 text-amber-900">{c}</p>)}<p>Alternativas: {row.alternatives.join(', ')||'Nenhuma registrada'}</p><p>ID observado: <span className="font-mono">{row.observed_template_id||'Não disponível'}</span></p></div>
 <label className="block text-sm font-medium">Template ID proposto<input aria-label="Template ID proposto" list="proposal-catalog" className={control+' mt-1 w-full font-mono'} disabled={!pending||busy} value={review.template_id} onChange={e=>{set({template_id:e.target.value.trim(),activity_ids:[],set_current:false});setResolved(false);}}/></label><datalist id="proposal-catalog">{catalog.map(t=><option key={t.template_id} value={t.template_id}>{t.title}</option>)}</datalist>
 <p className="text-xs text-slate-600">O ID preserva a caixa. A sugestão contextual não altera o link extraído nem comprova que a peça foi enviada.</p>
 <label className="flex items-start gap-2 text-sm"><input type="checkbox" disabled={!pending||busy||!loaded} checked={review.set_current} onChange={e=>set({set_current:e.target.checked,expected_current_id:current?.id||null})}/>Escolher este texto como versão atual</label>
 {current&&<details><summary className="cursor-pointer text-xs text-cyan-800">Comparar com o texto atual</summary><MessagePreview content={current.payload} compact/></details>}
 <section className="space-y-2 rounded-lg border p-3"><h3 className="text-sm font-semibold">Vínculos históricos opcionais</h3><p className="text-xs text-slate-600">Sem seleção de disparos, a aprovação registra somente conteúdo e uso configurado.</p><div className="flex flex-wrap gap-2"><label className="text-xs">Início<input aria-label="Início comprovado" type="date" className={control+' block w-full'} disabled={!pending||busy} value={review.start_date||''} onChange={e=>set({start_date:e.target.value||null,activity_ids:[]})}/></label><label className="text-xs">Fim<input aria-label="Fim comprovado" type="date" className={control+' block w-full'} disabled={!pending||busy} value={review.end_date||''} onChange={e=>set({end_date:e.target.value||null,activity_ids:[]})}/></label></div><label className="block text-xs">Evidência do período<input aria-label="Evidência do período" className={control+' mt-1 w-full'} disabled={!pending||busy} value={review.evidence} onChange={e=>set({evidence:e.target.value,activity_ids:[]})}/></label>
 {!loaded&&<p className="text-xs">Consultando execuções e versões…</p>}{loaded&&<p className="text-xs">{exact.length} execuções da mesma jornada/canal · {eligible.length} elegíveis no período escolhido.</p>}
 {eligible.map(a=><label key={a.id} className="flex items-start gap-2 text-xs"><input type="checkbox" disabled={!pending||busy||!review.evidence.trim()} checked={review.activity_ids.includes(a.id)} onChange={e=>set({activity_ids:e.target.checked?[...review.activity_ids,a.id]:review.activity_ids.filter(id=>id!==a.id)})}/>{localDay(a.dispatch_date)} · {a.id} {a.template_id?'(já vinculado ao mesmo ID)':''}</label>)}
 {exact.some(a=>a.template_id&&a.template_id!==review.template_id)&&<p className="text-xs text-amber-800">Existem vínculos com outro ID; eles serão preservados.</p>}</section>
 {pending&&<><label className="block text-sm">Motivo da revisão<textarea aria-label="Motivo da revisão" className={control+' mt-1 w-full'} value={note} disabled={busy} onChange={e=>setNote(e.target.value)} placeholder="Confirme a proposta ou explique a correção e o reuso intencional"/></label><label className="flex items-start gap-2 text-sm"><input type="checkbox" disabled={busy} checked={resolved} onChange={e=>setResolved(e.target.checked)}/>Revisei o ID, o conteúdo e o público; as divergências foram resolvidas para esta aprovação</label></>}
 <section className="rounded-lg border p-3 text-xs"><h3 className="font-semibold">Reuso de texto no acervo aprovado</h3>{reuse?<><p className="mt-1 text-slate-600">Cobertura: {reuse.coverage.approved_versions} versões com texto · {reuse.coverage.linked_activities} execuções com template. Comparação exata do texto normalizado.</p>{reuse.matches.map(r=><p key={r.content_id} className="mt-2 break-all"><strong className="font-mono">{r.template_id}</strong> · {r.linked_activities} execuções vinculadas ao ID · {r.same_context_activities} no mesmo parceiro/segmento · última data {r.last_dispatch?localDay(r.last_dispatch):'não comprovada'}</p>)}{!reuse.matches.length&&<p className="mt-2">Nenhum texto equivalente no acervo aprovado consultado. Histórico sem texto fica fora desta comparação.</p>}<p className="mt-2 text-slate-600">Vínculo ao ID não certifica qual versão foi enviada. Reuso pode ser intencional; não mede repetição por pessoa.</p></>:<p className="mt-1">Consulta ainda não disponível.</p>}</section>
 <details className="text-xs"><summary className="cursor-pointer text-cyan-800">Fonte e atribuição</summary><p className="mt-2 break-all">{p.link_url||'Sem link extraído'}</p><pre className="whitespace-pre-wrap">{JSON.stringify({utm:p.utm,context:row.resolved_context,analysis_id:row.analysis_id},null,2)}</pre></details>
 </div><div><MessagePreview content={p.content} compact/><p className="mt-2 text-xs text-slate-600">Prévia do conteúdo configurado no pacote; não certifica envio histórico.</p></div></div></div>
 <footer className="space-y-2 border-t p-4">{error&&<p role="alert" className="text-sm text-red-700">{error}</p>}<div className="flex justify-end gap-2"><button className={control} onClick={onClose}>Fechar</button>{pending&&<button className={button+' inline-flex items-center gap-2'} disabled={busy||!loaded||!review.template_id||(resolved&&note.trim().length<3)} onClick={async()=>{setBusy(true);setError('');try{await saveProposal(row,{...review,expected_current_id:current?.id||null},resolved,note);onSaved();}catch(e){setError(describeError(e));}finally{setBusy(false);}}}><Check size={16}/>Salvar revisão</button>}</div></footer></div></div>,document.body);
}
