import {useEffect,useState} from 'react';
import {supabase} from '../../services/supabaseClient';
import {describeError} from '../../services/communicationService';
import {dispatchDay,type FrameworkActivity} from '../../utils/communicationOrchestrator';
interface Group {key:string;members:FrameworkActivity[];fingerprint:string;safe:boolean;kind:string;approved:boolean;keep_id:string|null}
export function ExecutionDuplicateReview({start,end,onChanged,sourceRevision}:{start:string;end:string;onChanged:()=>void;sourceRevision:unknown}) {
 const [groups,setGroups]=useState<Group[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[page,setPage]=useState(1),[note,setNote]=useState(''),[selected,setSelected]=useState<string[]>([]);
 useEffect(()=>{let active=true;setError('');setGroups([]);setSelected([]);setPage(1);supabase.rpc('read_execution_duplicates',{p_start:start,p_end:end}).then(({data,error})=>{if(active){if(error){setError(describeError(error));setGroups([]);}else setGroups(data||[]);}});return()=>{active=false;};},[start,end,revision,sourceRevision]);
 const eligible=groups.filter(g=>g.safe&&!g.approved),pending=groups.filter(g=>!g.approved);
 async function review(items:Group[],approved:boolean){setBusy(true);setError('');try{for(const g of items){const keep=g.members.find(m=>m.template_id)||g.members[0];const {error}=await supabase.rpc('review_execution_duplicate',{p_ids:g.members.map(m=>m.id),p_keep:keep.id,p_fingerprint:g.fingerprint,p_approved:approved,p_note:note});if(error)throw error;}}catch(e){setError(describeError(e));}finally{setBusy(false);setRevision(v=>v+1);onChanged();}}
 return <details className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs"><summary className="cursor-pointer font-semibold text-slate-600">Revisão de execuções repetidas · {pending.length} grupos no período · {eligible.length} candidatos compatíveis</summary>
 <p className="my-2 text-slate-600">Mesmo nome e data não bastam. Apenas pares idênticos ou com template vazio/preenchido podem contar como uma execução após sua aprovação. Originais preservados; mudança na fonte invalida a decisão. A consolidação vale para as métricas desta fila.</p>
 {error&&<p role="alert" className="text-red-700">{error}</p>}
 <div className="my-2 flex flex-wrap gap-2"><input aria-label="Justificativa da consolidação" className="min-w-48 flex-1 rounded border px-2 py-1" placeholder="Justificativa da revisão" value={note} onChange={e=>setNote(e.target.value)}/><button disabled={busy||!eligible.length} className="rounded border px-2 py-1 disabled:opacity-40" onClick={()=>setSelected(eligible.map(g=>g.key))}>Selecionar compatíveis</button><button disabled={busy||!selected.length||note.trim().length<3} className="rounded bg-emerald-600 px-2 py-1 font-semibold text-white disabled:opacity-40" onClick={()=>void review(eligible.filter(g=>selected.includes(g.key)),true)}>Aprovar {selected.length} consolidações</button></div>
 {groups.slice((page-1)*10,page*10).map(g=><div key={g.key} className="mb-1 flex flex-wrap items-center gap-2 rounded border p-2"><input aria-label={'Consolidar '+g.members[0]['Activity name / Taxonomia']} type="checkbox" disabled={busy||!g.safe||g.approved} checked={selected.includes(g.key)} onChange={e=>setSelected(e.target.checked?[...selected,g.key]:selected.filter(k=>k!==g.key))}/><span className="min-w-0 flex-1"><strong>{g.kind}</strong> · {g.members[0]['Data de Disparo']?dispatchDay(g.members[0]['Data de Disparo']!):'Sem data'}<p className="break-all text-xs text-slate-600">{g.members[0]['Activity name / Taxonomia']} · {g.members[0].jornada}</p></span><span>{g.members.length} registros · {g.approved?'Consolidação aprovada':g.safe?'Aguardando decisão':'Revisão individual'}</span>{g.approved&&<button disabled={busy||note.trim().length<3} className="text-cyan-700 underline disabled:opacity-40" onClick={()=>void review([g],false)}>Desfazer consolidação</button>}<details className="w-full"><summary className="cursor-pointer text-cyan-700">Comparar fontes</summary>{g.members.map(m=><pre key={m.id} className="my-1 max-h-48 overflow-auto whitespace-pre-wrap break-all rounded bg-slate-50 p-2 text-xs">{JSON.stringify(m,null,2)}</pre>)}</details></div>)}
 {!groups.length&&!error&&<p className="text-slate-600">Sem grupos repetidos neste período.</p>}
 {groups.length>10&&<div className="flex justify-end gap-3"><button disabled={page===1} onClick={()=>setPage(page-1)}>Anterior</button><span>{page} / {Math.ceil(groups.length/10)}</span><button disabled={page*10>=groups.length} onClick={()=>setPage(page+1)}>Próxima</button></div>}
 </details>;
}
