import {ChevronRight,CalendarClock,AlertTriangle,Check,Link2Off} from 'lucide-react';
import type {CommunicationTemplate} from '../../types/communication';
import type {ProposalRow} from '../../services/communicationProposalService';
import type {Orchestration} from '../../utils/communicationOrchestrator';
import {dispatchDay,missingGovernanceParameters} from '../../utils/communicationOrchestrator';
import {CommunicationVisual} from './previews/CommunicationVisual';
import {DimTag,fmtDay,type TagKind} from './ui/commsUi';
const fmt=(v:number|null)=>v==null?'sem dado':v.toLocaleString('pt-BR',{notation:v>=1000?'compact':'standard',maximumFractionDigits:1});
const tags:[string,TagKind][]=[['front','front'],['partner','partner'],['channel','channel'],['segment','segment'],['subgroup','subgroup'],['offer','offer'],['campaign','campaign'],['creditVariant','segment'],['reuse','segment']];
export const STATUS_LABEL:Record<string,string>={ready:'Pronta',review:'Com pendências',applied:'Enviada',technical:'Opt-out',rejected:'Rejeitada'};
const STATUS_TONE:Record<string,string>={ready:'bg-emerald-50 text-emerald-800 ring-emerald-200',review:'bg-amber-50 text-amber-900 ring-amber-300',applied:'bg-cyan-50 text-cyan-900 ring-cyan-200',technical:'bg-slate-100 text-slate-700 ring-slate-200',rejected:'bg-red-50 text-red-800 ring-red-200'};
export function ReconciliationProposalRow({row,o,open,checked,busy,onToggle,onSelect,onReview,onMoment,reuse,template}:{template?:CommunicationTemplate;row:ProposalRow;o:Orchestration;open:boolean;checked:boolean;busy:boolean;onToggle:()=>void;onSelect:()=>void;onReview:(templateId?:string)=>void;onMoment:()=>void;reuse:string}) {
 const p=row.message.payload,pending=['ready','review'].includes(row.status),conflicts=[...row.conflicts,...o.conflicts];
 const status=row.status==='ready'&&o.conflicts.length&&!row.reviewed_by?'review':row.status;
 const missing=p.is_optout?[]:missingGovernanceParameters(row);
 const detailsId='proposal-details-'+row.id;
 return <article data-proposal-row={row.id} aria-label={'Comunicação '+(row.proposed_template_id||p.activity_name)} className={`overflow-hidden rounded-xl border bg-white transition-shadow ${open?'border-cyan-500 shadow-md':'border-slate-200 hover:border-slate-300'}`}>
  <div className="flex flex-wrap items-center gap-3 px-4 py-3 xl:flex-nowrap">
   <input type="checkbox" className="h-4 w-4" aria-label={'Selecionar '+p.activity_name} disabled={busy||!pending} checked={checked} onChange={onSelect}/>
   <CommunicationVisual content={p.content} template={template}/>
   <div className="min-w-0 flex-1 basis-64 xl:basis-auto">
    <div className="flex flex-wrap items-center gap-2"><code className="max-w-[420px] truncate font-mono text-sm font-semibold text-slate-900" title={row.proposed_template_id}>{row.proposed_template_id||'Template ID a definir'}</code><button onClick={onMoment} className="inline-flex items-center gap-1 rounded-md border border-cyan-300 bg-white px-2 py-1 text-xs font-semibold text-cyan-800 hover:bg-cyan-50" title="Editar o momento na régua"><CalendarClock size={12} aria-hidden="true"/>{o.moment.label} · confiança {o.moment.confidence}</button></div>
    <div className="mt-1.5 flex flex-wrap gap-1">{tags.map(([key,kind])=>{const f=o.fields[key];return !f||f.value==='Não identificado'?null:<DimTag key={key} kind={kind} label={f.label} value={f.value} source={f.source} conflict={f.conflict}/>;})}</div>
    {missing.length>0&&<p className="mt-1.5 flex items-center gap-1 text-xs text-amber-900"><Link2Off size={12} aria-hidden="true"/>Link sem {missing.join(', ')}. O ID e as etiquetas são uma proposta da análise.</p>}
    <p className="mt-1 truncate text-xs text-slate-600" title={p.activity_name+'\n'+p.journey_name}>{p.activity_name} · {p.journey_name} · versão {p.journey_version}</p>
   </div>
   <dl className="flex shrink-0 items-center gap-4 text-xs tabular-nums text-slate-600" title="Volume dos registros no período; não representa pessoas únicas nem certifica a versão enviada">
    <div><dt className="sr-only">Base</dt><dd><b className="text-sm text-slate-900">{fmt(o.base)}</b> base</dd><dd>{fmt(o.actionable)} acionável</dd></div>
    <div><dt className="sr-only">Execuções</dt><dd><b className="text-sm text-slate-900">{o.exec}</b> {o.exec===1?'execução':'execuções'}</dd><dd>{o.latest?'última '+fmtDay(dispatchDay(o.latest)):'sem data'}</dd></div>
   </dl>
   <div className="flex w-36 shrink-0 flex-col items-stretch gap-1.5">
    <span className={'inline-flex items-center justify-center gap-1 rounded-md px-2 py-1 text-xs font-bold ring-1 '+(STATUS_TONE[status]||STATUS_TONE.technical)}>{status==='ready'?<Check size={12} aria-hidden="true"/>:status==='review'?<AlertTriangle size={12} aria-hidden="true"/>:null}{STATUS_LABEL[status]||status}</span>
    {conflicts.length>0&&<span className="text-center text-xs text-amber-900">{conflicts.length} {conflicts.length===1?'divergência':'divergências'}</span>}
    <button onClick={()=>onReview()} className={'rounded-lg px-3 py-2 text-sm font-bold text-white focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-cyan-700 '+(conflicts.length?'bg-amber-600 hover:bg-amber-700':'bg-cyan-700 hover:bg-cyan-800')}>{pending?'Revisar':'Consultar'}</button>
    <button aria-expanded={open} aria-controls={detailsId} onClick={onToggle} className="inline-flex items-center justify-center gap-1 text-xs font-semibold text-cyan-800 hover:underline"><ChevronRight size={14} aria-hidden="true" className={`transition-transform ${open?'rotate-90':''}`}/>{open?'Ocultar detalhes':'Ver detalhes'}</button>
   </div>
  </div>
  {open&&<div id={detailsId} className="grid gap-5 border-t border-slate-200 bg-slate-50 p-4 text-sm text-slate-700 md:grid-cols-2">
   <section><h3 className="mb-2 text-xs font-bold uppercase tracking-wide text-slate-600">Por que essa sugestão</h3>{row.reasons.map((r,i)=><p key={i} className="mb-1 flex gap-1.5 text-emerald-900"><Check size={14} aria-hidden="true" className="mt-0.5 shrink-0"/>{r}</p>)}{conflicts.length>0&&<><h4 className="mt-3 text-xs font-bold uppercase tracking-wide text-amber-900">Divergências</h4>{conflicts.map((r,i)=><p key={i} className="mb-1 flex gap-1.5 text-amber-900"><AlertTriangle size={14} aria-hidden="true" className="mt-0.5 shrink-0"/>{r}</p>)}</>}<p className="mt-2 text-cyan-900">{reuse}</p>
    <h4 className="mt-4 font-semibold text-slate-900">Alternativas do catálogo</h4>{o.candidates.length?o.candidates.map(c=><div key={c.id} className="mt-2 rounded-lg border border-slate-200 bg-white p-2.5"><code className="break-all font-semibold text-slate-900">{c.id}</code><p className="text-xs text-slate-600">Pontuação {c.score}/100 · não é probabilidade</p><p className="text-xs text-slate-700">{c.reasons.join(' · ')}</p>{c.conflicts.map((r,i)=><p key={i} className="text-xs text-amber-900">{r}</p>)}{pending&&<button onClick={()=>onReview(c.id)} className="mt-1 text-sm font-semibold text-cyan-800 underline">Revisar com este ID</button>}</div>):<p className="mt-1 text-slate-600">Sem candidato compatível com canal e público no catálogo consultado.</p>}
    {row.alternatives.length>0&&<p className="mt-3">Alternativas da análise: {row.alternatives.join(' · ')}</p>}
   </section>
   <section><h3 className="mb-2 text-xs font-bold uppercase tracking-wide text-slate-600">Etiquetas e fontes</h3><div className="grid grid-cols-2 gap-1.5 lg:grid-cols-3">{Object.entries(o.fields).filter(([key,f])=>f.value!=='Não identificado'&&(key!=='origin'||f.value!==o.fields.partner.value)).map(([key,f])=><div key={key} className={'rounded-lg border bg-white px-2.5 py-2 '+(f.conflict?'border-amber-300':'border-slate-200')}><span className="block text-xs font-bold uppercase text-slate-600">{f.label}</span><strong className="block text-sm text-slate-900">{f.value}</strong><p className="mt-1 text-xs text-slate-600">{f.source}</p>{f.alternatives.map((a,i)=><p key={i} className={'text-xs '+(f.conflict?'text-amber-900':'text-slate-600')}>{a.value} · {a.source}</p>)}</div>)}</div>
    <p className="mt-3 break-all"><strong>ID no link:</strong> {row.observed_template_id||'sem af_sub3 no link'} · <strong>Proposto:</strong> {row.proposed_template_id||'a definir'}</p>
    <h4 className="mt-3 font-semibold text-slate-900">Partes do Template ID</h4><div className="mt-1 flex flex-wrap gap-1">{o.templateParts.map((part,i)=><span key={i} className="rounded bg-white px-2 py-1 text-xs ring-1 ring-slate-200">{part.label}: {part.value}</span>)}</div>
    <h4 className="mt-3 font-semibold text-slate-900">Origem no pacote SFMC</h4><p className="mt-1 break-all">Jornada: {p.journey_name} · versão {p.journey_version}</p><p className="mt-1 break-all">Activity Name: {p.activity_name}</p><p className="mt-1">DE de entrada: {p.entry_de||'não extraída'} · Condição: {p.entry_filter||'não extraída'}</p><p className="mt-1">Nome do template Meta: {p.content.meta_template_name||'não extraído'}</p><details className="mt-1"><summary className="cursor-pointer font-semibold text-cyan-800">Link e registro técnico</summary><p className="mt-1 break-all">{p.link_url||'Sem link extraído'}</p><pre className="mt-1 whitespace-pre-wrap break-all text-xs">{JSON.stringify({utm:p.utm,analysis_id:row.analysis_id,revision:row.revision,reviewed_by:row.reviewed_by,updated_at:row.updated_at,occurrence_key:p.occurrence_key},null,2)}</pre></details>
    <h4 className="mt-3 font-semibold text-slate-900">Momento e caminho na jornada</h4>{o.moment.reasons.map((r,i)=><p key={i} className="mt-1">{r}</p>)}{o.moment.alternatives.map((r,i)=><p key={i} className="text-amber-900">Alternativa: {r}</p>)}{p.paths.map((path,i)=><p key={i} className="mt-2">{path.labels.join(' → ')}{path.waits.length?' · Esperas: '+path.waits.join(' + '):''}</p>)}
    <h4 className="mt-3 font-semibold text-slate-900">Resultados no período</h4><div className="mt-1 flex flex-wrap gap-2">{o.results.filter(r=>r.covered>0||['Propostas','Aprovados','Cartões Gerados','Cliques'].includes(r.label)).map(r=><span key={r.label} className="rounded border border-slate-200 bg-white px-2 py-1 text-xs">{r.label}: {fmt(r.value)} <span className="text-slate-600">({r.covered} de {r.total} registros)</span></span>)}</div><p className="mt-1 text-xs text-slate-600">Resultados das execuções do período; não atribuídos automaticamente à versão do texto do pacote.</p>
    <h4 className="mt-3 font-semibold text-slate-900">Execuções no período</h4><p>{o.exec} {o.exec===1?'registro':'registros'} · {o.otherContexts} com o mesmo Activity Name em outros contextos, fora das métricas.</p><p className="mt-1">{row.review.start_date?`Vínculo histórico: ${fmtDay(row.review.start_date)} a ${fmtDay(row.review.end_date)}`:'Período do vínculo histórico ainda não confirmado'} · {row.review.activity_ids.length} disparo(s) selecionado(s)</p>
    {o.relatedActivities.length>0&&<details className="mt-2"><summary className="cursor-pointer font-semibold text-cyan-800">{o.relatedActivities.length} execuções com contexto parecido</summary><p className="mt-1 text-xs text-slate-600">Candidatos fora das métricas desta comunicação. Não autorizam vínculo histórico.</p>{o.relatedActivities.slice(0,10).map(a=><p key={a.id} className="mt-1 break-all text-xs">{a.jornada} · {a['Activity name / Taxonomia']} · {a.template_id||'sem template'} · ordem {a['Ordem de disparo']??'desconhecida'}</p>)}</details>}
    <details className="mt-2"><summary className="cursor-pointer font-semibold text-cyan-800">Registros e vínculos existentes</summary>{o.activities.map(a=><p key={a.id} className="mt-1 break-all text-xs">{a['Data de Disparo']?fmtDay(dispatchDay(a['Data de Disparo'])):'Sem data'} · {a.template_id||'sem template vinculado'} · ordem {a['Ordem de disparo']??'desconhecida'}</p>)}</details>
   </section>
  </div>}
 </article>;
}
