import {ChevronRight,CalendarClock,Sparkles,AlertTriangle} from 'lucide-react';
import type {CommunicationTemplate} from '../../types/communication';
import type {ProposalRow} from '../../services/communicationProposalService';
import type {Orchestration} from '../../utils/communicationOrchestrator';
import {dispatchDay,missingGovernanceParameters} from '../../utils/communicationOrchestrator';
import {CommunicationVisual} from './previews/CommunicationVisual';
const fmt=(v:number|null)=>v==null?'—':v.toLocaleString('pt-BR',{notation:v>=1000?'compact':'standard',maximumFractionDigits:1});
const tags=['front','partner','channel','segment','subgroup','offer','campaign'];
export function ReconciliationProposalRow({row,o,open,checked,busy,onToggle,onSelect,onReview,onMoment,reuse,template}:{template?:CommunicationTemplate;row:ProposalRow;o:Orchestration;open:boolean;checked:boolean;busy:boolean;onToggle:()=>void;onSelect:()=>void;onReview:(templateId?:string)=>void;onMoment:()=>void;reuse:string}) {
 const p=row.message.payload,pending=['ready','review'].includes(row.status),conflicts=[...row.conflicts,...o.conflicts];
 const status=row.status==='ready'&&o.conflicts.length&&!row.reviewed_by?'review':row.status;
 return <article data-proposal-row={row.id} className={`overflow-hidden rounded-xl border bg-white transition-shadow ${open?'border-cyan-400 shadow-md':'border-slate-200 hover:border-slate-300'}`}>
  <div className="flex flex-wrap items-center gap-3 px-4 py-3 xl:flex-nowrap">
   <input type="checkbox" aria-label={'Selecionar '+p.activity_name} disabled={busy||!pending} checked={checked} onChange={onSelect}/>
   <button aria-label={'Expandir '+p.activity_name} aria-expanded={open} onClick={onToggle}><ChevronRight size={15} className={`text-slate-400 transition-transform ${open?'rotate-90 text-cyan-600':''}`}/></button>
   <CommunicationVisual content={p.content} template={template}/>
   <div className="min-w-0 flex-1 basis-64 xl:basis-auto">
    <div className="flex flex-wrap items-center gap-2"><code className="max-w-[400px] truncate font-mono text-xs font-semibold text-slate-800" title={row.proposed_template_id}>{row.proposed_template_id||'Template ID a definir'}</code><button onClick={onMoment} className="inline-flex items-center gap-1 rounded-md border border-cyan-200 px-2 py-1 text-[10px] font-bold text-cyan-700" title={o.moment.reasons.join('\n')}><CalendarClock size={11}/>{o.moment.label} · {o.moment.confidence}</button></div>
    <div className="mt-1 flex flex-wrap gap-1">{tags.map(key=>{const f=o.fields[key];return f.value==='Não identificado'?null:<span key={key} title={f.label+': '+f.source+(f.conflict?' · fontes divergentes':'')} className={'rounded-md px-1.5 py-0.5 text-[10.5px] font-semibold ring-1 '+(f.conflict?'bg-amber-50 text-amber-800 ring-amber-200':'bg-slate-100 text-slate-600 ring-slate-200/70')}>{f.value}</span>;})}</div>
    {!p.is_optout&&missingGovernanceParameters(row).length>0&&<p className="mt-1 text-[10px] text-amber-700">Sem parâmetros: {missingGovernanceParameters(row).join(', ')} · classificação proposta</p>}
    <p className="mt-1 truncate text-[10px] text-slate-400" title={p.activity_name+'\n'+p.journey_name}>↳ {p.activity_name} · {p.journey_name} · v{p.journey_version}</p>
   </div>
   <div className="flex shrink-0 items-center gap-3.5 text-[11px] tabular-nums text-slate-500" title="Volume acumulado dos registros no recorte; não representa pessoas únicas nem certifica a versão enviada">
    <span><b className="text-slate-800">{fmt(o.base)}</b> base<br/><span className="text-[10px]">{fmt(o.actionable)} acionável</span></span><span><b className="text-slate-800">{o.exec}</b> exec</span><span className="text-slate-400">{o.latest?dispatchDay(o.latest):'Sem execução'}</span>
   </div>
   <div className="flex max-w-36 flex-wrap gap-1 text-[10px]"><span className={'rounded-full px-2 py-0.5 font-bold '+(status==='ready'?'bg-emerald-50 text-emerald-700':status==='review'?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-600')}>{({ready:'Pronta',review:'Revisar',applied:'Aplicada',technical:'Técnica',rejected:'Rejeitada'})[status]}</span>{conflicts.length>0&&<span className="rounded-full bg-amber-50 px-2 py-0.5 text-amber-700" title={conflicts.join('\n')}>{conflicts.length} divergências</span>}</div>
   <div className="flex shrink-0 gap-1.5"><button onClick={onToggle} className="inline-flex items-center gap-1.5 rounded-lg border border-cyan-200 px-3 py-2 text-xs font-bold text-cyan-700 hover:bg-cyan-50"><Sparkles size={13}/>Sugestões</button><button onClick={()=>onReview()} className={'rounded-lg px-3 py-2 text-xs font-bold text-white '+(conflicts.length?'bg-amber-500':'bg-cyan-600')}>{pending?'Revisar':'Consultar'}</button></div>
  </div>
  {open&&<div className="grid gap-5 border-t border-slate-100 bg-slate-50 p-4 text-xs md:grid-cols-2">
   <section><h3 className="mb-2 text-[10px] font-bold uppercase text-slate-400">Por que essa sugestão</h3>{row.reasons.map((r,i)=><p key={i} className="mb-1 text-emerald-800">✓ {r}</p>)}{conflicts.map((r,i)=><p key={i} className="mb-1 text-amber-800"><AlertTriangle size={11} className="inline"/> {r}</p>)}<p className="mt-2 text-cyan-800">{reuse}</p>
    <h4 className="mt-4 font-semibold">Alternativas do motor do catálogo</h4>{o.candidates.length?o.candidates.map(c=><div key={c.id} className="mt-2 rounded-lg border bg-white p-2"><code className="break-all font-semibold">{c.id}</code><p className="text-[10px] text-slate-500">Pontuação {c.score}/100 · não é probabilidade</p>{c.reasons.map((r,i)=><span key={i} className="mr-2 inline-block text-[10px]">{r}</span>)}{c.conflicts.map((r,i)=><p key={i} className="text-amber-800">⚠ {r}</p>)}{pending&&<button onClick={()=>onReview(c.id)} className="mt-1 text-cyan-700 underline">Revisar com este ID</button>}</div>):<p className="mt-1 text-slate-500">Sem candidato compatível com canal e público no catálogo consultado.</p>}
    {row.alternatives.length>0&&<p className="mt-3">Alternativas da análise: {row.alternatives.join(' · ')}</p>}
   </section>
   <section><h3 className="mb-2 text-[10px] font-bold uppercase text-slate-400">Anatomia e fontes do Framework</h3><div className="grid grid-cols-2 gap-1.5 lg:grid-cols-3">{Object.entries(o.fields).map(([key,f])=><div key={key} className="rounded-lg border bg-white px-2 py-1.5"><span className="block text-[9px] font-bold uppercase text-slate-400">{f.label}</span><strong className="block text-[11px]">{f.value}</strong><p className="mt-1 text-[9px] text-slate-500">{f.source}</p>{f.alternatives.map((a,i)=><p key={i} className={'text-[9px] '+(f.conflict?'text-amber-800':'text-slate-400')}>{a.value} · {a.source}</p>)}</div>)}</div>
    <p className="mt-3 break-all"><strong>ID observado:</strong> {row.observed_template_id||'Sem af_sub3 no link'} · <strong>Proposto:</strong> {row.proposed_template_id||'A definir'}</p>
    <h4 className="mt-3 font-semibold">Decomposição do Template ID</h4><div className="mt-1 flex flex-wrap gap-1">{o.templateParts.map((part,i)=><span key={i} className="rounded bg-white px-2 py-1 ring-1 ring-slate-200">{part.label}: {part.value}</span>)}</div>
    <h4 className="mt-3 font-semibold">Estrutura e origem do pack</h4><p className="mt-1 break-all">Jornada: {p.journey_name} · versão {p.journey_version} · origem {p.journey_origin_id}</p><p className="mt-1 break-all">Activity Name: {p.activity_name} · chave {p.activity_key}</p><p className="mt-1">DE de entrada: {p.entry_de||'Não extraída'} · Condição: {p.entry_filter||'Não extraída'}</p><p className="mt-1">Asset: {p.asset_name||'Não extraído'} · Nome Meta: {p.content.meta_template_name||'Não extraído'}</p><details className="mt-1"><summary className="cursor-pointer text-cyan-700">Tracking e revisão da análise</summary><p className="mt-1 break-all">{p.link_url||'Sem link extraído'}</p><pre className="mt-1 whitespace-pre-wrap break-all text-[10px]">{JSON.stringify({utm:p.utm,analysis_id:row.analysis_id,revision:row.revision,reviewed_by:row.reviewed_by,updated_at:row.updated_at,occurrence_key:p.occurrence_key},null,2)}</pre></details>
    <h4 className="mt-3 font-semibold">Momento e ramo</h4>{o.moment.reasons.map((r,i)=><p key={i} className="mt-1">{r}</p>)}{o.moment.alternatives.map((r,i)=><p key={i} className="text-amber-800">Alternativa: {r}</p>)}{p.paths.map((path,i)=><p key={i} className="mt-2">{path.labels.join(' → ')}{path.waits.length?' · Esperas: '+path.waits.join(' + '):''}</p>)}
    <h4 className="mt-3 font-semibold">Resultados registrados no recorte</h4><div className="mt-1 flex flex-wrap gap-2">{o.results.map(r=><span key={r.label} title={'Cobertura: '+r.covered+' de '+r.total+' registros'} className="rounded border bg-white px-2 py-1">{r.label}: {fmt(r.value)} <span className="text-slate-400">({r.covered}/{r.total})</span></span>)}</div><p className="mt-1 text-slate-500">Resultados das execuções; não atribuídos automaticamente à versão do texto do pack.</p>
    <h4 className="mt-3 font-semibold">Execuções no recorte</h4><p>{o.exec} registros · {o.otherContexts} registros com o mesmo Activity Name em outros contextos, excluídos das métricas.</p><p className="mt-1 text-slate-500">A execução associada à jornada não comprova qual versão do conteúdo foi enviada. Somar bases não mede pessoas únicas.</p><p className="mt-1">{row.review.start_date?`${row.review.start_date} → ${row.review.end_date}`:'Período para vínculo histórico ainda não confirmado'} · {row.review.activity_ids.length} alvo(s) selecionado(s)</p>
    {o.relatedActivities.length>0&&<details className="mt-2"><summary className="cursor-pointer text-cyan-700">{o.relatedActivities.length} execuções com contexto semelhante</summary><p className="mt-1 text-slate-500">Candidatos do universo consultado, fora das métricas desta ocorrência. Não autorizam vínculo histórico.</p>{o.relatedActivities.slice(0,10).map(a=><p key={a.id} className="mt-1 break-all">{a.jornada} · {a['Activity name / Taxonomia']} · {a.template_id||'Sem template'} · ordem {a['Ordem de disparo']??'desconhecida'}</p>)}</details>}
    <details className="mt-2"><summary className="cursor-pointer text-cyan-700">Registros e vínculos existentes</summary>{o.activities.map(a=><p key={a.id} className="mt-1 break-all">{a['Data de Disparo']?dispatchDay(a['Data de Disparo']):'Sem data'} · {a.id} · {a.template_id||'Sem template vinculado'} · ordem {a['Ordem de disparo']??'desconhecida'}</p>)}</details>
   </section>
  </div>}
 </article>;
}
