create table if not exists public.appsflyer_source_mappings (
  media_source_raw text primary key,
  media_source_canonical text not null,
  origin_group text not null,
  channel text,
  active boolean not null default true,
  notes text,
  updated_at timestamptz not null default now(),
  constraint appsflyer_source_mappings_origin_check
    check (origin_group in ('organico', 'pago', 'crm', 'parceiro'))
);

comment on table public.appsflyer_source_mappings is
  'Taxonomia governada de media sources AppsFlyer para origem e canal no GaaS.';

create table if not exists public.appsflyer_collection_runs (
  id bigint generated by default as identity primary key,
  source_type text not null,
  status text not null,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  date_from date,
  date_to date,
  max_business_date date,
  row_count integer not null default 0,
  quality_summary jsonb not null default '{}'::jsonb,
  error_message text,
  constraint appsflyer_collection_runs_status_check
    check (status in ('pending', 'complete', 'partial', 'failed', 'blocked')),
  constraint appsflyer_collection_runs_row_count_check
    check (row_count >= 0)
);

comment on table public.appsflyer_collection_runs is
  'Auditoria de snapshots e futuras coletas agregadas/raw do AppsFlyer.';

create table if not exists public.appsflyer_acquisition_daily (
  business_date date not null,
  app_scope text not null default 'afinz_b2c',
  app_id text,
  platform text,
  media_source text not null,
  media_source_canonical text not null,
  origin_group text not null,
  campaign text,
  channel text,
  geo text,
  sub_param_1 text,
  installs bigint not null default 0,
  sessions bigint not null default 0,
  clicks bigint not null default 0,
  impressions bigint,
  cost numeric(18, 6),
  currency text not null default 'USD',
  metric_status jsonb not null default jsonb_build_object(
    'installs', 'confirmed',
    'sessions', 'confirmed',
    'clicks', 'confirmed',
    'impressions', 'not_available',
    'cost', 'not_available'
  ),
  quality_status text not null default 'complete',
  source_type text not null default 'appsflyer_aggregated_snapshot',
  source_updated_at timestamptz,
  imported_at timestamptz not null default now(),
  constraint appsflyer_acquisition_daily_origin_check
    check (origin_group in ('organico', 'pago', 'crm', 'parceiro')),
  constraint appsflyer_acquisition_daily_quality_check
    check (quality_status in ('complete', 'partial', 'directional', 'suspect', 'blocked')),
  constraint appsflyer_acquisition_daily_nonnegative_check
    check (
      installs >= 0
      and sessions >= 0
      and clicks >= 0
      and (impressions is null or impressions >= 0)
      and (cost is null or cost >= 0)
    )
);

comment on table public.appsflyer_acquisition_daily is
  'Aquisição diária AppsFlyer. Snapshot P0 no grão data x media source; dimensões futuras permanecem nulas até coleta certificada.';

comment on column public.appsflyer_acquisition_daily.sessions is
  'Volume de sessões no período; intensidade de uso, não etapa de conversão única.';

comment on column public.appsflyer_acquisition_daily.sub_param_1 is
  'Segmento de atribuição quando disponível no agregado. Não equivale ao af_param_1 do evento.';

create unique index if not exists appsflyer_acquisition_daily_grain_uidx
  on public.appsflyer_acquisition_daily (
    business_date,
    app_scope,
    coalesce(app_id, ''),
    coalesce(platform, ''),
    media_source,
    coalesce(campaign, ''),
    coalesce(channel, ''),
    coalesce(geo, ''),
    coalesce(sub_param_1, '')
  );

create index if not exists appsflyer_acquisition_daily_date_idx
  on public.appsflyer_acquisition_daily (business_date);

create index if not exists appsflyer_acquisition_daily_origin_source_idx
  on public.appsflyer_acquisition_daily (origin_group, media_source_canonical);

create index if not exists appsflyer_acquisition_daily_campaign_idx
  on public.appsflyer_acquisition_daily (campaign)
  where campaign is not null;

insert into public.appsflyer_source_mappings (
  media_source_raw,
  media_source_canonical,
  origin_group,
  channel,
  notes
)
values
  ('organic', 'organic', 'organico', 'organic', 'Sem atribuição de mídia.'),
  ('Facebook Ads', 'facebook_ads', 'pago', 'meta', 'Fonte paga Meta.'),
  ('googleadwords_int', 'google_ads', 'pago', 'google_ads', 'Fonte paga Google Ads.'),
  ('CRM', 'crm', 'crm', 'crm', 'Alias legado em caixa alta.'),
  ('crm', 'crm', 'crm', 'crm', 'Fonte governada pid=crm.'),
  ('WhatsApp', 'whatsapp', 'crm', 'whatsapp', 'Clique-app originado em WhatsApp.'),
  ('SMS', 'sms', 'crm', 'sms', 'Clique-app originado em SMS.'),
  ('Cross_sale', 'cross_sale', 'crm', 'cross_sell', 'Cross-sell próprio.'),
  ('Blog', 'blog', 'crm', 'owned_content', 'Conteúdo próprio.'),
  ('Acordo_Certo', 'acordo_certo', 'parceiro', 'partner', 'Parceiro Acordo Certo.'),
  ('Serasa', 'serasa', 'parceiro', 'partner', 'Parceiro Serasa.'),
  ('espaco_laser', 'espaco_laser', 'parceiro', 'partner', 'Parceiro Espaço Laser.'),
  ('hirota', 'hirota', 'parceiro', 'partner', 'Parceiro Hirota.'),
  ('outros', 'outros', 'parceiro', 'partner', 'Demais parceiros.')
on conflict (media_source_raw) do update
set
  media_source_canonical = excluded.media_source_canonical,
  origin_group = excluded.origin_group,
  channel = excluded.channel,
  notes = excluded.notes,
  active = true,
  updated_at = now();

alter table public.appsflyer_source_mappings enable row level security;
alter table public.appsflyer_collection_runs enable row level security;
alter table public.appsflyer_acquisition_daily enable row level security;

revoke all on table public.appsflyer_source_mappings from anon, authenticated;
revoke all on table public.appsflyer_collection_runs from anon, authenticated;
revoke all on table public.appsflyer_acquisition_daily from anon, authenticated;

grant select on table public.appsflyer_source_mappings to authenticated;
grant select on table public.appsflyer_collection_runs to authenticated;
grant select on table public.appsflyer_acquisition_daily to authenticated;

grant all on table public.appsflyer_source_mappings to service_role;
grant all on table public.appsflyer_collection_runs to service_role;
grant all on table public.appsflyer_acquisition_daily to service_role;
grant usage, select on sequence public.appsflyer_collection_runs_id_seq to service_role;

drop policy if exists "appsflyer_source_mappings_authenticated_read"
  on public.appsflyer_source_mappings;
create policy "appsflyer_source_mappings_authenticated_read"
  on public.appsflyer_source_mappings
  for select
  to authenticated
  using (true);

drop policy if exists "appsflyer_collection_runs_authenticated_read"
  on public.appsflyer_collection_runs;
create policy "appsflyer_collection_runs_authenticated_read"
  on public.appsflyer_collection_runs
  for select
  to authenticated
  using (true);

drop policy if exists "appsflyer_acquisition_daily_authenticated_read"
  on public.appsflyer_acquisition_daily;
create policy "appsflyer_acquisition_daily_authenticated_read"
  on public.appsflyer_acquisition_daily
  for select
  to authenticated
  using (true);
